/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poultry_farm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HOOKE GEN
 */
public class Egg_collection_form extends javax.swing.JFrame {
    Connection con;
    Statement st;
    String cs;
    
    String user;
    String password;
    
    String query;
    ResultSet rs;
   
    public Egg_collection_form() {
        con = null;
        st = null;
        cs = "jdbc:mysql://localhost:3306/poultry_farm";
        user = "root";
        password = "henry";
        setTitle("Egg Collection");
        initComponents();
        populatePoultryHouseCombo();
        txtCollection_round.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCollection_round = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txt_ID = new javax.swing.JTextField();
        comboPoultry_house = new javax.swing.JComboBox<>();
        txtNumber_of_trays = new javax.swing.JTextField();
        txtExtra_eggs = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 9, -1, -1));

        jLabel2.setText("Dtae and Time");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 43, -1, -1));

        jLabel3.setText("Poultry House");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 77, -1, -1));

        jLabel4.setText("Collection Round");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 111, -1, -1));

        jLabel5.setText("Number of Trays");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 142, -1, -1));

        jLabel6.setText("Extra Eggs");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 170, -1, -1));

        jLabel7.setText("Total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 204, -1, -1));
        getContentPane().add(txtCollection_round, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 108, 262, -1));
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 40, 262, -1));
        getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 6, 262, -1));

        comboPoultry_house.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboPoultry_house, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 74, 262, -1));
        getContentPane().add(txtNumber_of_trays, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 139, 262, -1));
        getContentPane().add(txtExtra_eggs, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 167, 262, -1));

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 201, 262, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 241, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 241, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOOKE GEN\\Documents\\NetBeansProjects\\Poultry_Farm\\poultry_pictures\\eggs.jpg")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            String s1 = txt_ID.getText();   
            String s2 = txtDate.getText();
            String s3 = (String)comboPoultry_house.getSelectedItem();
            String s4 = txtCollection_round.getText();
            String s5 = txtNumber_of_trays.getText();
            String s6 = txtExtra_eggs.getText();
            String s7 = txtTotal.getText();
            
            /*checking if there is data entered in the ID field*/
            if (!s1.isEmpty() || !s2.isEmpty() || !s7.isEmpty()) {
                JOptionPane.showMessageDialog(this,"This field must be empty as it is auto-generated. Please clear this field.","Invalid ID Input",JOptionPane.ERROR_MESSAGE);
                if(!s1.isEmpty()){
                   txt_ID.requestFocus(); 
                   txt_ID.selectAll();
                }
                else if(!s2.isEmpty()){
                    txtDate.requestFocus();
                    txtDate.selectAll();
                 }
                else{
                    txtTotal.requestFocus();
                    txtTotal.selectAll();
                }
                return;
            }
            
            /*checking for empty fields*/
            if(s3 == null|| s4.isEmpty() || s5.isEmpty() || s6.isEmpty() || s3.equals("--Select the poultry house ID---")){
                JOptionPane.showMessageDialog(this,"Please fill all required fields","Validation Error",JOptionPane.ERROR_MESSAGE);
                if(s3 == null){
                    comboPoultry_house.requestFocus();
                }
                else if(s4.isEmpty()){
                    txtCollection_round.requestFocus();
                }
                else if(s5.isEmpty()){
                    txtNumber_of_trays.requestFocus();
                }
                else if(s3.equals("--Select the poultry house ID---")){
                    comboPoultry_house.requestFocus();
                }
                else{
                    txtExtra_eggs.requestFocus();
                }
                return;
            }
            
            /*check number is positive*/
            if(!s4.matches("\\d+")){
                JOptionPane.showMessageDialog(this,"Collection round must be a positive whole number", "Invalid Data Type",JOptionPane.ERROR_MESSAGE);
                txtCollection_round.requestFocus();
                txtCollection_round.selectAll();
                return;
            }
            if (!s5.matches("\\d+")){
                JOptionPane.showMessageDialog(this,"Number of trays must be a positive whole number", "Invalid Data Type",JOptionPane.ERROR_MESSAGE);
                txtNumber_of_trays.requestFocus();
                txtNumber_of_trays.selectAll();
                return;
            }
            if (!s6.matches("\\d+")){
                JOptionPane.showMessageDialog(this,"Number of extra eggs must be a positive whole number", "Invalid Data Type",JOptionPane.ERROR_MESSAGE);
                txtExtra_eggs.requestFocus();
                txtExtra_eggs.selectAll();
                return;
            }
                
            int collection_round = Integer.parseInt(s4);
            int number_of_trays = Integer.parseInt(s5);
            int extra_eggs = Integer.parseInt(s6);
            if(collection_round < 0){
                JOptionPane.showMessageDialog(this,"Collection round cannot be negative","Invalid Value",JOptionPane.ERROR_MESSAGE);
                txtCollection_round.requestFocus();
                txtCollection_round.selectAll();
                return;
            }
            if(number_of_trays < 0){
                JOptionPane.showMessageDialog(this,"Number of trays cannot be negative","Invalid Value",JOptionPane.ERROR_MESSAGE);
                txtNumber_of_trays.requestFocus();
                txtNumber_of_trays.selectAll();
                return;
            }
            if(extra_eggs < 0){
                JOptionPane.showMessageDialog(this,"Number of extra eggs cannot be negative","Invalid Value",JOptionPane.ERROR_MESSAGE);
                txtExtra_eggs.requestFocus();
                txtExtra_eggs.selectAll();
                return;
            }
            
            /*calculate the total*/
            int total_eggs = (number_of_trays * 30) + extra_eggs;
            txtTotal.setText(String.valueOf(total_eggs));
            Connection con = null;
            PreparedStatement pstmt = null;
            
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
               query = "INSERT INTO egg_collection (Poultry_house_ID, Collection_round, Number_of_trays, Extra_eggs, total_of_eggs) VALUES (?, ?, ?, ?, ?)";
                pstmt = con.prepareStatement(query);
                int poultryhouse_id = Integer.parseInt(s3);
                pstmt.setInt(1, poultryhouse_id);
                pstmt.setInt(2, collection_round);
                pstmt.setInt(3, number_of_trays);
                pstmt.setInt(4, extra_eggs);
                pstmt.setInt(5, total_eggs);
                
                /*validate saving*/
                int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to Save this record","Confirm Save",JOptionPane.YES_NO_OPTION);
        
                if (confirm != JOptionPane.YES_OPTION) {
                    return; // User cancelled1
                }
                
                int rowsaffected = pstmt.executeUpdate();
                if(rowsaffected > 0){
                    JOptionPane.showMessageDialog(null,"Record Saved Successfully");
                    txt_ID.setText("");
                    txtExtra_eggs.setText("");
                    txtNumber_of_trays.setText("");
                    txtCollection_round.setText("");
                    comboPoultry_house.setSelectedIndex(-1);
                    txtTotal.setText("");

                    txtCollection_round.requestFocus();
                }
                else {
                    JOptionPane.showMessageDialog(this, "Failed to save record","Error",JOptionPane.ERROR_MESSAGE);
                }
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        else {
            this.dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Worker_form().setVisible(true);
            }
        });
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Egg_collection_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Egg_collection_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Egg_collection_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Egg_collection_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Egg_collection_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboPoultry_house;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCollection_round;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtExtra_eggs;
    private javax.swing.JTextField txtNumber_of_trays;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txt_ID;
    // End of variables declaration//GEN-END:variables

    private void populatePoultryHouseCombo() {
         Connection localCon = null;
        Statement localSt = null;
        ResultSet localRs = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            localCon = DriverManager.getConnection(cs, user, password);
            localSt = localCon.createStatement();
            query = "SELECT ID FROM poultry_house"; // Adjust table/column name as needed
            localRs = localSt.executeQuery(query);
            
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("--Select the poultry house ID---");
            while (localRs.next()) {
                model.addElement(localRs.getString("ID"));
            }
            comboPoultry_house.setModel(model);
            
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error loading poultry houses: " + ex.getMessage(), 
                "Database Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } finally {
            try {
                if (localRs != null) localRs.close();
                if (localSt != null) localSt.close();
                if (localCon != null) localCon.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

}
