/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poultry_farm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HOOKE GEN
 */
public class Employees_form extends javax.swing.JFrame {

    Connection con;
    Statement st;
    String cs;
    
    String user;
    String password;
    
    String query;
    ResultSet rs;
    public Employees_form() {
        setTitle("Employees Details");
        initComponents();
        con = null;
        st = null;
        cs = "jdbc:mysql://localhost:3306/poultry_farm";
        user = "root";
        password = "henry";
        populateBranchCombo();
        comboBranch.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDistrict = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        comboRole = new javax.swing.JComboBox<>();
        txtNames = new javax.swing.JTextField();
        comboBranch = new javax.swing.JComboBox<>();
        txt_ID = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 9, -1, -1));

        jLabel2.setText("Branch");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 43, -1, -1));

        jLabel3.setText("Names");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 77, -1, -1));

        jLabel4.setText("Role");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 111, -1, -1));

        jLabel5.setText("Contact");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 145, -1, -1));

        jLabel6.setText("District of Birth");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 179, -1, -1));

        jLabel7.setText("Age");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 213, -1, -1));

        jLabel8.setText("salary");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 247, -1, -1));
        getContentPane().add(txtDistrict, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 176, 274, -1));
        getContentPane().add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 210, 274, -1));
        getContentPane().add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 244, 274, -1));
        getContentPane().add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 142, 274, -1));

        comboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select the role--", "Worker", "Manager", "Veterinary DR", "Driver", "Builder" }));
        getContentPane().add(comboRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 108, 274, -1));
        getContentPane().add(txtNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 74, 274, -1));

        comboBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 40, 274, -1));
        getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 6, 274, -1));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 284, -1, -1));

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 284, -1, -1));

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 284, -1, -1));

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 284, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 284, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 284, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 284, -1, -1));

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        getContentPane().add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 284, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOOKE GEN\\Documents\\NetBeansProjects\\Poultry_Farm\\poultry_pictures\\financial_transact.jpg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
         String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a Branch or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM employees WHERE ID < ? ORDER By ID DESC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                     String foundID = rs.getString("ID");
                    String Branch_ID = rs.getString("Branch_ID");
                    String Name_of_employee = rs.getString("Name_of_employee");
                    String Role_of_employee = rs.getString("Role_of_employee");
                    String Contact = rs.getString("Contact");
                    String District_of_Birth = rs.getString("District_of_Birth");
                    String  Age = rs.getString("Age");
                    String Salary = rs.getString("Salary");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    comboBranch.setSelectedItem(Branch_ID);
                    txtNames.setText(Name_of_employee);
                    comboRole.setSelectedItem(Role_of_employee);
                    txtContact.setText(Contact);
                    txtDistrict.setText(District_of_Birth);
                    txtAge.setText(Age);
                    txtSalary.setText(Salary);
                    
                }
                else {
                    JOptionPane.showMessageDialog(this, "This is the first record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                
}
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
                  }
        
   
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        else {
            this.dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_form().setVisible(true);
            }
        });
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String s1 = txt_ID.getText();
         
         //check if ID is entered
         if ( s1.isEmpty()){
             JOptionPane.showMessageDialog(this, "Please enter the reord ID to search", "Error", JOptionPane.ERROR_MESSAGE);
             txt_ID.requestFocus();
             return;
         }
         
         /*check if positive integer is entered*/
        if (!s1.matches("\\d+")) {
            JOptionPane.showMessageDialog(this,"ID must be a positive whole number","Invalid ID Format",JOptionPane.ERROR_MESSAGE);
            txt_ID.requestFocus();
            txt_ID.selectAll();
            return;
    }
            
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM employees WHERE ID = ?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1,s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Branch_ID = rs.getString("Branch_ID");
                    String Name_of_employee = rs.getString("Name_of_employee");
                    String Role_of_employee = rs.getString("Role_of_employee");
                    String Contact = rs.getString("Contact");
                    String District_of_Birth = rs.getString("District_of_Birth");
                    String  Age = rs.getString("Age");
                    String Salary = rs.getString("Salary");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    comboBranch.setSelectedItem(Branch_ID);
                    txtNames.setText(Name_of_employee);
                    comboRole.setSelectedItem(Role_of_employee);
                    txtContact.setText(Contact);
                    txtDistrict.setText(District_of_Birth);
                    txtAge.setText(Age);
                    txtSalary.setText(Salary);
                    JOptionPane.showMessageDialog(null,"Record Retrieved Successfully");
                }
                //no record found
                else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Not Found", JOptionPane.WARNING_MESSAGE);
                    clearFields();
                    txt_ID.requestFocus();
                }
                
}
             catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM employees ORDER By ID ASC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                     String foundID = rs.getString("ID");
                    String Branch_ID = rs.getString("Branch_ID");
                    String Name_of_employee = rs.getString("Name_of_employee");
                    String Role_of_employee = rs.getString("Role_of_employee");
                    String Contact = rs.getString("Contact");
                    String District_of_Birth = rs.getString("District_of_Birth");
                    String  Age = rs.getString("Age");
                    String Salary = rs.getString("Salary");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    comboBranch.setSelectedItem(Branch_ID);
                    txtNames.setText(Name_of_employee);
                    comboRole.setSelectedItem(Role_of_employee);
                    txtContact.setText(Contact);
                    txtDistrict.setText(District_of_Birth);
                    txtAge.setText(Age);
                    txtSalary.setText(Salary);
                    JOptionPane.showMessageDialog(null,"First Record Retrieved Successfully");
                     }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }

                }
        
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
       try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM employees ORDER By ID DESC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                     String foundID = rs.getString("ID");
                    String Branch_ID = rs.getString("Branch_ID");
                    String Name_of_employee = rs.getString("Name_of_employee");
                    String Role_of_employee = rs.getString("Role_of_employee");
                    String Contact = rs.getString("Contact");
                    String District_of_Birth = rs.getString("District_of_Birth");
                    String  Age = rs.getString("Age");
                    String Salary = rs.getString("Salary");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    comboBranch.setSelectedItem(Branch_ID);
                    txtNames.setText(Name_of_employee);
                    comboRole.setSelectedItem(Role_of_employee);
                    txtContact.setText(Contact);
                    txtDistrict.setText(District_of_Birth);
                    txtAge.setText(Age);
                    txtSalary.setText(Salary);
                    JOptionPane.showMessageDialog(null,"Last Record Retrieved Successfully");
                     }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }

                }                                        
 
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
       String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a Branch or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM employees WHERE ID > ? ORDER By ID ASC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                     String foundID = rs.getString("ID");
                    String Branch_ID = rs.getString("Branch_ID");
                    String Name_of_employee = rs.getString("Name_of_employee");
                    String Role_of_employee = rs.getString("Role_of_employee");
                    String Contact = rs.getString("Contact");
                    String District_of_Birth = rs.getString("District_of_Birth");
                    String  Age = rs.getString("Age");
                    String Salary = rs.getString("Salary");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    comboBranch.setSelectedItem(Branch_ID);
                    txtNames.setText(Name_of_employee);
                    comboRole.setSelectedItem(Role_of_employee);
                    txtContact.setText(Contact);
                    txtDistrict.setText(District_of_Birth);
                    txtAge.setText(Age);
                    txtSalary.setText(Salary);
                    
                }
                else {
                    JOptionPane.showMessageDialog(this, "This is the last record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                
}
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
                  }
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       String s1 = txt_ID.getText();
	if (s1.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please first find the record in the branches to delete", "Error", JOptionPane.ERROR_MESSAGE);
        txt_ID.requestFocus();
        return;
    }
        
			
	try {
            Class.forName("com.mysql.cj.jdbc.Driver"); // register the driver,
            con = DriverManager.getConnection(cs, user, password);
            String deletequery = "DELETE FROM employees WHERE ID = ?";
            PreparedStatement deleteStmt = con.prepareStatement(deletequery);
            deleteStmt.setString(1, s1);
            int confirm = JOptionPane.showConfirmDialog(this, "Are you Sure You want to Delete Branch with ID: " + s1 + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm != JOptionPane.YES_OPTION){
                return; //user cancelled
            }
            else{
                int rowsAffected = deleteStmt.executeUpdate();
             if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Record deleted successfully!");
                    // Clear fields after successful deletion
                    clearFields();
                }
            
            else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Error", JOptionPane.ERROR_MESSAGE);
            } 
        }
        }
        catch (SQLException ex) 
        {
            ex.printStackTrace();
	} 
        catch (ClassNotFoundException e) 
        {
            e.printStackTrace();
	} 
        finally {

            try {
		if (st != null) 
                {
                    st.close();
		}
		if (con != null) 
                {
                    con.close();
		}

            } 
            catch (SQLException ex) 
            {
                ex.printStackTrace();
            }
	}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            String s1 = txt_ID.getText();   
            String s2 = (String) comboBranch.getSelectedItem();
            String s3 = txtNames.getText();
            String s4 = (String) comboRole.getSelectedItem();
            String s5 = txtContact.getText();
            String s6 = txtDistrict.getText();
            String s7 = txtAge.getText();
            String s8 = txtSalary.getText();
            
            /*checking if there is data entered in the ID field*/
            if (!s1.isEmpty()) {
                JOptionPane.showMessageDialog(this,"This field must be empty as it is auto-generated. Please clear this field.","Invalid ID Input",JOptionPane.ERROR_MESSAGE);
                txt_ID.requestFocus(); 
                txt_ID.selectAll();
                return;
            }
            
            /*checking for empty fields*/
            if(s2 == null|| s4.equals("--Select the role--") || s5.isEmpty() || s6.isEmpty() || s2.equals("--Select the Branch ID---") || s3.isEmpty() || s7.isEmpty() || s8.isEmpty()){
                JOptionPane.showMessageDialog(this,"Please fill all required fields","Validation Error",JOptionPane.ERROR_MESSAGE);
                if(s3 == null){
                    comboBranch.requestFocus();
                }
                else if(s4.equals("--Select the role--")){
                    comboRole.requestFocus();
                }
                else if(s3.isEmpty()){
                    txtNames.requestFocus();
                }
                else if(s3.equals("--Select the Branch ID---")){
                    comboBranch.requestFocus();
                }
                else if(s5.isEmpty()){
                    txtContact.requestFocus();
                }
                else if(s6.isEmpty()){
                    txtDistrict.requestFocus();
                }
                else if(s7.isEmpty()){
                    txtAge.requestFocus();
                }
                else if(s8.isEmpty()){
                    txtSalary.requestFocus();
                }
                return;
            }
            
            /*check number is positive*/
            if(!s5.matches("\\d+")){
                JOptionPane.showMessageDialog(this,"Phone number cannot have characters", "Invalid Data Type",JOptionPane.ERROR_MESSAGE);
                txtContact.requestFocus();
                txtContact.selectAll();
                return;
            }
            if (!s7.matches("\\d+")){
                JOptionPane.showMessageDialog(this,"Age must be a positive whole number", "Invalid Data Type",JOptionPane.ERROR_MESSAGE);
                txtAge.requestFocus();
                txtAge.selectAll();
                return;
            }
            if (!s8.matches("\\d+(\\.\\d{0,2})?")){
                JOptionPane.showMessageDialog(this,"Salary must be a positive number with upto 2 decimal places", "Invalid Data Type",JOptionPane.ERROR_MESSAGE);
                txtSalary.requestFocus();
                txtSalary.selectAll();
                return;
            }
            if(!s3.matches("^[a-zA-Z\\s\\-\\'\\,]+$")){
                JOptionPane.showMessageDialog(this, "Names cannot contain integers","Invalid Location Format", 
                JOptionPane.ERROR_MESSAGE);
                txtNames.requestFocus();
                txtNames.selectAll();
                return;
            }
            if(!s6.matches("^[a-zA-Z\\s\\-\\'\\,]+$")){
                JOptionPane.showMessageDialog(this, "District cannot contain integers","Invalid Location Format", 
                JOptionPane.ERROR_MESSAGE);
                txtDistrict.requestFocus();
                txtDistrict.selectAll();
                return;
            }
            if(s5.length() > 10){
               JOptionPane.showMessageDialog(this,"Contact is too long (max 10 characters)","Invalid Location",JOptionPane.ERROR_MESSAGE);
                txtContact.requestFocus();
                txtContact.selectAll();
                return; 
            }
                
            int age = Integer.parseInt(s7);
            double salary = Double.parseDouble(s8);
            
            if(age < 0){
                JOptionPane.showMessageDialog(this,"Age cannot be negative","Invalid Value",JOptionPane.ERROR_MESSAGE);
                txtAge.requestFocus();
                txtAge.selectAll();
                return;
            }
            if(salary < 0){
                JOptionPane.showMessageDialog(this,"Salary cannot be negative","Invalid Value",JOptionPane.ERROR_MESSAGE);
                txtSalary.requestFocus();
                txtSalary.selectAll();
                return;
            }
            
            Connection con = null;
            PreparedStatement pstmt = null;
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
               query = "INSERT INTO employees (Branch_ID, Name_of_employee, Role_of_employee, Contact,  District_of_Birth, Age, Salary) VALUES (?, ?, ?, ?, ?,?,?)";
                pstmt = con.prepareStatement(query);
                
                pstmt.setString(1, s2);
                pstmt.setString(2, s3);
                pstmt.setString(3, s4);
                pstmt.setString(4, s5);
                pstmt.setString(5, s6);
                pstmt.setInt(6, age);
                pstmt.setDouble(7,salary);
                
                /*validate saving*/
                int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to Save this record","Confirm Save",JOptionPane.YES_NO_OPTION);
        
                if (confirm != JOptionPane.YES_OPTION) {
                    return; // User cancelled1
                }
                
                int rowsaffected = pstmt.executeUpdate();
                if(rowsaffected > 0){
                    JOptionPane.showMessageDialog(null,"Record Saved Successfully");
                    clearFields();

                    comboBranch.requestFocus();
                }
                else {
                    JOptionPane.showMessageDialog(this, "Failed to save record","Error",JOptionPane.ERROR_MESSAGE);
                }
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employees_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboBranch;
    private javax.swing.JComboBox<String> comboRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDistrict;
    private javax.swing.JTextField txtNames;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txt_ID;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        txt_ID.setText("");
        comboBranch.setSelectedItem("--Select the Branch ID---");
        txtNames.setText("");
        comboRole.setSelectedItem("--Select the role--");
        txtContact.setText("");
        txtDistrict.setText("");
        txtAge.setText("");
        txtSalary.setText("");
    }
    private void populateBranchCombo() {
         Connection localCon = null;
        Statement localSt = null;
        ResultSet localRs = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            localCon = DriverManager.getConnection(cs, user, password);
            localSt = localCon.createStatement();
            query = "SELECT ID FROM branches"; // Adjust table/column name as needed
            localRs = localSt.executeQuery(query);
            
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("--Select the Branch ID---");
            while (localRs.next()) {
                model.addElement(localRs.getString("ID"));
            }
            comboBranch.setModel(model);
            
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error loading ID: " + ex.getMessage(), 
                "Database Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } finally {
            try {
                if (localRs != null) localRs.close();
                if (localSt != null) localSt.close();
                if (localCon != null) localCon.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

}
