/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poultry_farm;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HOOKE GEN
 */
public class Equipment_maintenance_form extends javax.swing.JFrame {

    Connection con;
    Statement st;
    String cs;
    
    String user;
    String password;
    
    String query;
    ResultSet rs;
    
    public Equipment_maintenance_form() {
        con = null;
        st = null;
        cs = "jdbc:mysql://localhost:3306/poultry_farm";
        user = "root";
        password = "henry";
        setTitle("Equipment Maintenance");
        initComponents();
        populatePeformedbyCombo();
        txtEquipment.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtScheduled_date = new javax.swing.JTextField();
        txtPerformed_date = new javax.swing.JTextField();
        comboPerformedby = new javax.swing.JComboBox<>();
        txtCost = new javax.swing.JTextField();
        txtNotes = new javax.swing.JTextField();
        txtEquipment = new javax.swing.JTextField();
        txt_ID = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        comboMaintenace_type = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 9, -1, -1));

        jLabel2.setText("Equipment");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 43, -1, -1));

        jLabel3.setText("Maintenance Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 77, -1, -1));

        jLabel4.setText("Scheduled Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 111, -1, -1));

        jLabel5.setText("Performed Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 145, -1, -1));

        jLabel6.setText("Performed By");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 179, -1, -1));

        jLabel7.setText("Cost");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 213, -1, -1));

        jLabel8.setText("Notes");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 247, -1, -1));
        getContentPane().add(txtScheduled_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 108, 276, -1));
        getContentPane().add(txtPerformed_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 142, 276, -1));

        comboPerformedby.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboPerformedby, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 176, 276, -1));
        getContentPane().add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 210, 276, -1));
        getContentPane().add(txtNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 244, 276, -1));
        getContentPane().add(txtEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 40, 276, -1));

        txt_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 6, 276, -1));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 284, -1, -1));

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 284, -1, -1));

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 284, -1, -1));

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 284, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 284, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 284, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 284, -1, -1));

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        getContentPane().add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 284, -1, -1));

        comboMaintenace_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select a maintenance type--", "ROUTINE", "REPAIR", "CALIBRATION", "CLEANING" }));
        getContentPane().add(comboMaintenace_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 74, 276, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOOKE GEN\\Documents\\NetBeansProjects\\Poultry_Farm\\poultry_pictures\\financial_transact.jpg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a record or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM equipment_maintenance  WHERE ID < ? ORDER By ID DESC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                    String foundID = rs.getString("ID");
                    String Equipment_name = rs.getString("Equipment_name");
                    String Maintenance_Type = rs.getString("Maintenance_Type");
                    String Scheduled_date = rs.getString("Scheduled_date");
                    String Performed_date = rs.getString("Performed_date");
                    String Peformed_by = rs.getString("Performed_by");
                    String Cost = rs.getString("Cost");
                    String Notes = rs.getString("Notes");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtEquipment.setText(Equipment_name);
                    comboMaintenace_type.setSelectedItem(Maintenance_Type);
                    txtScheduled_date.setText(Scheduled_date);
                    txtPerformed_date.setText(Performed_date);
                    comboPerformedby.setSelectedItem(Peformed_by);
                    txtCost.setText(Cost);
                    txtNotes.setText(Notes);
                }
                //no record found
                else {
                    JOptionPane.showMessageDialog(this, "This is the last record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        else {
            this.dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_form().setVisible(true);
            }
        });
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a record or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM equipment_maintenance  WHERE ID > ? ORDER By ID ASC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                    String foundID = rs.getString("ID");
                    String Equipment_name = rs.getString("Equipment_name");
                    String Maintenance_Type = rs.getString("Maintenance_Type");
                    String Scheduled_date = rs.getString("Scheduled_date");
                    String Performed_date = rs.getString("Performed_date");
                    String Peformed_by = rs.getString("Performed_by");
                    String Cost = rs.getString("Cost");
                    String Notes = rs.getString("Notes");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtEquipment.setText(Equipment_name);
                    comboMaintenace_type.setSelectedItem(Maintenance_Type);
                    txtScheduled_date.setText(Scheduled_date);
                    txtPerformed_date.setText(Performed_date);
                    comboPerformedby.setSelectedItem(Peformed_by);
                    txtCost.setText(Cost);
                    txtNotes.setText(Notes);
                }
                //no record found
                else {
                    JOptionPane.showMessageDialog(this, "This is the last record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
         String s1 = txt_ID.getText();
         
         //check if ID is entered
         if ( s1.isEmpty()){
             JOptionPane.showMessageDialog(this, "Please enter the ID of the  to search", "Error", JOptionPane.ERROR_MESSAGE);
             txt_ID.requestFocus();
             return;
         }
         
         /*check if positive integer is entered*/
        if (!s1.matches("\\d+")) {
            JOptionPane.showMessageDialog(this,"ID must be a positive whole number","Invalid ID Format",JOptionPane.ERROR_MESSAGE);
            txt_ID.requestFocus();
            txt_ID.selectAll();
            return;
    }
            
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM equipment_maintenance WHERE ID = ?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1,s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Equipment_name = rs.getString("Equipment_name");
                    String Maintenance_Type = rs.getString("Maintenance_Type");
                    String Scheduled_date = rs.getString("Scheduled_date");
                    String Performed_date = rs.getString("Performed_date");
                    String Peformed_by = rs.getString("Performed_by");
                    String Cost = rs.getString("Cost");
                    String Notes = rs.getString("Notes");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtEquipment.setText(Equipment_name);
                    comboMaintenace_type.setSelectedItem(Maintenance_Type);
                    txtScheduled_date.setText(Scheduled_date);
                    txtPerformed_date.setText(Performed_date);
                    comboPerformedby.setSelectedItem(Peformed_by);
                    txtCost.setText(Cost);
                    txtNotes.setText(Notes);
                    JOptionPane.showMessageDialog(null,"Record Retrieved Successfully");
                }
                //no record found
                else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Not Found", JOptionPane.WARNING_MESSAGE);
                    clearFields();
                    txt_ID.requestFocus();
                }
                
}
             catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM equipment_maintenance ORDER By ID ASC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                    String foundID = rs.getString("ID");
                    String Equipment_name = rs.getString("Equipment_name");
                    String Maintenance_Type = rs.getString("Maintenance_Type");
                    String Scheduled_date = rs.getString("Scheduled_date");
                    String Performed_date = rs.getString("Performed_date");
                    String Peformed_by = rs.getString("Performed_by");
                    String Cost = rs.getString("Cost");
                    String Notes = rs.getString("Notes");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtEquipment.setText(Equipment_name);
                    comboMaintenace_type.setSelectedItem(Maintenance_Type);
                    txtScheduled_date.setText(Scheduled_date);
                    txtPerformed_date.setText(Performed_date);
                    comboPerformedby.setSelectedItem(Peformed_by);
                    txtCost.setText(Cost);
                    txtNotes.setText(Notes);
                JOptionPane.showMessageDialog(null,"First Record Retrieved Successfully");
                }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
        }
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
         try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM equipment_maintenance ORDER By ID DESC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                    String foundID = rs.getString("ID");
                    String Equipment_name = rs.getString("Equipment_name");
                    String Maintenance_Type = rs.getString("Maintenance_Type");
                    String Scheduled_date = rs.getString("Scheduled_date");
                    String Performed_date = rs.getString("Performed_date");
                    String Peformed_by = rs.getString("Performed_by");
                    String Cost = rs.getString("Cost");
                    String Notes = rs.getString("Notes");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtEquipment.setText(Equipment_name);
                    comboMaintenace_type.setSelectedItem(Maintenance_Type);
                    txtScheduled_date.setText(Scheduled_date);
                    txtPerformed_date.setText(Performed_date);
                    comboPerformedby.setSelectedItem(Peformed_by);
                    txtCost.setText(Cost);
                    txtNotes.setText(Notes);
                JOptionPane.showMessageDialog(null,"First Record Retrieved Successfully");
                }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
        }
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String s1 = txt_ID.getText();
	if (s1.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please first find the record in the database to delete", "Error", JOptionPane.ERROR_MESSAGE);
        txt_ID.requestFocus();
        return;
    }
        
			
	try {
            Class.forName("com.mysql.cj.jdbc.Driver"); // register the driver,
            con = DriverManager.getConnection(cs, user, password);
            String deletequery = "DELETE FROM equipment_maintenance WHERE ID = ?";
            PreparedStatement deleteStmt = con.prepareStatement(deletequery);
            deleteStmt.setString(1, s1);
            int confirm = JOptionPane.showConfirmDialog(this, "Are you Sure You want to Delete record with ID: " + s1 + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm != JOptionPane.YES_OPTION){
                return; //user cancelled
            }
            else{
                int rowsAffected = deleteStmt.executeUpdate();
             if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Record deleted successfully!");
                    // Clear fields after successful deletion
                    clearFields();
                }
            
            else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Error", JOptionPane.ERROR_MESSAGE);
            } 
        }
        }
        catch (SQLException ex) 
        {
            ex.printStackTrace();
	} 
        catch (ClassNotFoundException e) 
        {
            e.printStackTrace();
	} 
        finally {

            try {
		if (st != null) 
                {
                    st.close();
		}
		if (con != null) 
                {
                    con.close();
		}

            } 
            catch (SQLException ex) 
            {
                ex.printStackTrace();
            }
	}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String s1 = txt_ID.getText();   
            String s2 = txtEquipment.getText();
            String s3 = (String)comboMaintenace_type.getSelectedItem();
            String s4 = txtScheduled_date.getText();
            String s5 = txtPerformed_date.getText();
            String s6 = (String) comboPerformedby.getSelectedItem();
            String s7 = txtCost.getText();
            String s8 = txtNotes.getText();
            
            /*checking if there is data entered in the ID field*/
            if (!s1.isEmpty()) {
                JOptionPane.showMessageDialog(this,"This field must be empty as it is auto-generated. Please clear this field.","Invalid Input",JOptionPane.ERROR_MESSAGE);
                   txt_ID.requestFocus(); 
                   txt_ID.selectAll();
                   return;
}
            if (txtScheduled_date.getText().isEmpty()) {
                txtScheduled_date.setText("YYYY-MM-DD");
                txtScheduled_date.setForeground(Color.GRAY);
            }
            if (txtPerformed_date.getText().isEmpty()) {
                txtPerformed_date.setText("YYYY-MM-DD");
                txtPerformed_date.setForeground(Color.GRAY);
            }  
            
            /*checking for empty fields*/
            if(s6 == null|| s3.equals("--Select a maintenance type--") || s2.isEmpty() || s4.isEmpty() || s5.isEmpty() || s7.isEmpty() || s6.equals("--Select the ID of worker---") || s4.equals("YYYY-MM-DD")|| s5.equals("YYYY-MM-DD")){
                JOptionPane.showMessageDialog(this,"Please fill all required fields","Validation Error",JOptionPane.ERROR_MESSAGE);
                if(s6 == null){
                    comboPerformedby.requestFocus();
                }
                else if(s4.isEmpty() || s4.equals("YYYY-MM-DD")){
                    txtScheduled_date.requestFocus();
                }
                else if(s5.isEmpty() || s5.equals("YYYY-MM-DD")){
                    txtPerformed_date.requestFocus();
                }
                else if(s3.equals("--Select a maintenance type--")){
                    comboMaintenace_type.requestFocus();
                }
                else if(s6.equals("--Select the ID of worker---")){
                    comboPerformedby.requestFocus();
                }
                else if(s2.isEmpty()){
                    txtEquipment.requestFocus();
                }
                else{
                    txtCost.requestFocus();
                }
                return;
            }
            if (!isValidDate(s4)) {
                JOptionPane.showMessageDialog(this,"Scheduled date must be in YYYY-MM-DD format\nExample: 2025-09-17","Invalid Date Format",JOptionPane.ERROR_MESSAGE);
                txtScheduled_date.requestFocus();
                txtScheduled_date.selectAll();
                return;
    }
    
            if (!isValidDate(s5)) {
                JOptionPane.showMessageDialog(this,"Performed date must be in YYYY-MM-DD format\nExample: 2025-09-17","Invalid Date Format",JOptionPane.ERROR_MESSAGE);
                txtPerformed_date.requestFocus();
                txtPerformed_date.selectAll();
                return;
    }
            if (isDateAfter(s5, s4)) {
                JOptionPane.showMessageDialog(this,"Performed date should be after or equal to scheduled date","Date Logic Error",JOptionPane.ERROR_MESSAGE);
                txtPerformed_date.requestFocus();
                txtPerformed_date.selectAll();
                return;
    }
            
            /*check number is positive*/
            if(!s7.matches("^\\d+(\\.\\d{1,2})?$")){
                JOptionPane.showMessageDialog(this,"Cost must be a positive whole number", "Invalid Data Type",JOptionPane.ERROR_MESSAGE);
                txtCost.requestFocus();
                txtCost.selectAll();
                return;
            }
            if(s2.length() > 20){
               JOptionPane.showMessageDialog(this,"Equipment name is too long (max 20 characters)","Invalid Location",JOptionPane.ERROR_MESSAGE);
                txtEquipment.requestFocus();
                txtEquipment.selectAll();
                return; 
            }
                
            double cost = Double.parseDouble(s7);
            if(cost < 0){
                JOptionPane.showMessageDialog(this,"Cost cannot be negative","Invalid Value",JOptionPane.ERROR_MESSAGE);
                txtCost.requestFocus();
                txtCost.selectAll();
                return;
            }
            
            Connection con = null;
            PreparedStatement pstmt = null;
            
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                java.sql.Date scheduledDate = java.sql.Date.valueOf(s4);
                java.sql.Date performedDate = java.sql.Date.valueOf(s5);
                
               query = "INSERT INTO equipment_maintenance (Equipment_name, Maintenance_Type, Scheduled_date, Performed_date, Performed_by, Cost, Notes) VALUES (?, ?, ?, ?, ?,?,?)";
                pstmt = con.prepareStatement(query);
                pstmt.setString(1, s2);
                pstmt.setString(2, s3);
                pstmt.setDate(3, scheduledDate);
                pstmt.setDate(4, performedDate);
                pstmt.setString(5, s6);
                pstmt.setDouble(6, cost);
                pstmt.setString(7, s8);
                
                /*validate saving*/
                int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to Save this record","Confirm Save",JOptionPane.YES_NO_OPTION);
        
                if (confirm != JOptionPane.YES_OPTION) {
                    return; // User cancelled1
                }
                
                int rowsaffected = pstmt.executeUpdate();
                if(rowsaffected > 0){
                    JOptionPane.showMessageDialog(null,"Record Saved Successfully");
                    clearFields();
                    txtEquipment.requestFocus();
                }
                else {
                    JOptionPane.showMessageDialog(this, "Failed to save record","Error",JOptionPane.ERROR_MESSAGE);
                }
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnSaveActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipment_maintenance_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipment_maintenance_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipment_maintenance_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipment_maintenance_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equipment_maintenance_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboMaintenace_type;
    private javax.swing.JComboBox<String> comboPerformedby;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtEquipment;
    private javax.swing.JTextField txtNotes;
    private javax.swing.JTextField txtPerformed_date;
    private javax.swing.JTextField txtScheduled_date;
    private javax.swing.JTextField txt_ID;
    // End of variables declaration//GEN-END:variables
private void populatePeformedbyCombo() {
         Connection localCon = null;
        Statement localSt = null;
        ResultSet localRs = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            localCon = DriverManager.getConnection(cs, user, password);
            localSt = localCon.createStatement();
            query = "SELECT ID FROM employees"; // Adjust table/column name as needed
            localRs = localSt.executeQuery(query);
            
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("--Select the ID of worker---");
            while (localRs.next()) {
                model.addElement(localRs.getString("ID"));
            }
            comboPerformedby.setModel(model);
            
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error loading users: " + ex.getMessage(), 
                "Database Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } finally {
            try {
                if (localRs != null) localRs.close();
                if (localSt != null) localSt.close();
                if (localCon != null) localCon.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

    private void clearFields() {
        txt_ID.setText("");
        txtEquipment.setText("");
        comboMaintenace_type.setSelectedItem("--Select a maintenance type--");
        txtScheduled_date.setText("YYYY-MM-DD");
        txtScheduled_date.setForeground(Color.GRAY);
        txtPerformed_date.setText("YYYY-MM-DD");
        txtPerformed_date.setForeground(Color.GRAY);
        comboPerformedby.setSelectedItem("--Select the ID of worker---");
        txtCost.setText("");
        txtNotes.setText("");
    }
    private boolean isValidDate(String dateStr) {
        if (dateStr == null || !dateStr.matches("\\d{4}-\\d{2}-\\d{2}")) {
            return false;
        }

        try {
            java.sql.Date.valueOf(dateStr);
            return true;
        } catch (IllegalArgumentException e) {
            return false;
        }
}
    private boolean isDateAfter(String dateStr1, String dateStr2) {
    try {
        java.sql.Date date1 = java.sql.Date.valueOf(dateStr1);
        java.sql.Date date2 = java.sql.Date.valueOf(dateStr2);
        return date1.before(date2); 
    } catch (IllegalArgumentException e) {
        return false;
    }
}

}
