/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poultry_farm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
public class Expenses_form extends javax.swing.JFrame {

    Statement st;
    String cs;
    
    String user;
    String password;
    
    String query;
    ResultSet rs;
    Connection con;
    
    public Expenses_form() {
        setTitle("Expenses");
        initComponents();
        con = null;
        st = null;
        cs = "jdbc:mysql://localhost:3306/poultry_farm";
        user = "root";
        password = "henry";
        comboSupplier_id.requestFocus();
        populatecombosid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtExpense_type = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        comboBranch_id = new javax.swing.JComboBox<>();
        comboSupplier_id = new javax.swing.JComboBox<>();
        txt_ID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFirst1 = new javax.swing.JButton();
        btnLast1 = new javax.swing.JButton();
        btnNext1 = new javax.swing.JButton();
        btnPrevious1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 9, -1, -1));

        jLabel2.setText("Supplier");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 43, -1, -1));

        jLabel3.setText("Branch");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 77, -1, -1));

        jLabel4.setText("Type of Expense");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 108, -1, 22));

        jLabel5.setText("Amount");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 145, -1, -1));

        jLabel6.setText("Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 179, -1, -1));
        getContentPane().add(txtExpense_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 108, 329, -1));

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        getContentPane().add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 142, 329, -1));
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 176, 329, -1));

        comboBranch_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboBranch_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 74, 329, -1));

        comboSupplier_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboSupplier_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 40, 329, -1));
        getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 6, 329, -1));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 241, -1, -1));

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 241, -1, -1));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 241, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 241, -1, -1));

        btnFirst1.setText("First");
        btnFirst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirst1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnFirst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 241, -1, -1));

        btnLast1.setText("Last");
        btnLast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLast1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLast1, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 241, -1, -1));

        btnNext1.setText("Next");
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 241, -1, -1));

        btnPrevious1.setText("Previous");
        btnPrevious1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevious1, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 241, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOOKE GEN\\Documents\\NetBeansProjects\\Poultry_Farm\\poultry_pictures\\farm.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String s1 = txt_ID.getText();

        //check if ID is entered
        if ( s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter the reord ID to search", "Error", JOptionPane.ERROR_MESSAGE);
            txt_ID.requestFocus();
            return;
        }

        /*check if positive integer is entered*/
        if (!s1.matches("\\d+")) {
            JOptionPane.showMessageDialog(this,"ID must be a positive whole number","Invalid ID Format",JOptionPane.ERROR_MESSAGE);
            txt_ID.requestFocus();
            txt_ID.selectAll();
            return;
        }

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(cs, user, password);
            query = "SELECT * FROM expenses WHERE ID = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1,s1);

            rs = pst.executeQuery();
            if (rs.next()){
                //record found
                String foundID = rs.getString("ID");
                String Supplier_ID = rs.getString("Supplier_ID");
                String Branch_ID = rs.getString("Branch_ID");
                String Type_of_expense = rs.getString("Type_of_expense");
                String Amount = rs.getString("Amount");
                String Entry_Date = rs.getString("Entry_Date");

                //update the text fields
                txt_ID.setText(foundID);
                txtExpense_type.setText(Type_of_expense);
                comboSupplier_id.setSelectedItem(Supplier_ID);
                txtAmount.setText(Amount);
                comboBranch_id.setSelectedItem(Branch_ID);
                txtDate.setText(Entry_Date);
                JOptionPane.showMessageDialog(null,"Record Retrieved Successfully");
            }
            //no record found
            else {
                JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Not Found", JOptionPane.WARNING_MESSAGE);
                clearFields();
                comboSupplier_id.requestFocus();
            }

        }
        catch (SQLException ex){
            ex.printStackTrace();
        }
        catch (ClassNotFoundException e){
            e.printStackTrace();
        }
        finally {
            try{
                if (st != null){
                    st.close();
                }
                if (con != null){
                    con.close();
                }
            }
            catch (SQLException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String s1 = txt_ID.getText();
        if (s1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please first find the record in  to delete", "Error", JOptionPane.ERROR_MESSAGE);
            txt_ID.requestFocus();
            return;
        }

        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); // register the driver,
            con = DriverManager.getConnection(cs, user, password);
            String deletequery = "DELETE FROM expenses WHERE ID = ?";
            PreparedStatement deleteStmt = con.prepareStatement(deletequery);
            deleteStmt.setString(1, s1);
            int confirm = JOptionPane.showConfirmDialog(this, "Are you Sure You want to Delete Record with ID: " + s1 + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm != JOptionPane.YES_OPTION){
                return; //user cancelled
            }
            else{
                int rowsAffected = deleteStmt.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Record deleted successfully!");
                    // Clear fields after successful deletion
                    clearFields();
                    comboSupplier_id.requestFocus();
                }

                else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
        }
        catch (ClassNotFoundException e)
        {
            e.printStackTrace();
        }
        finally {

            try {
                if (st != null)
                {
                    st.close();
                }
                if (con != null)
                {
                    con.close();
                }

            }
            catch (SQLException ex)
            {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String s1 = txt_ID.getText();   
            String s2 = (String) comboSupplier_id.getSelectedItem();
            String s3 = txtExpense_type.getText();
            String s4 = txtAmount.getText();
            String s5 = (String) comboBranch_id.getSelectedItem();
            String s6 = txtDate.getText();
            
            /*checking if there is data entered in the ID field*/
            if (!s1.isEmpty() || !s6.isEmpty()) {
                JOptionPane.showMessageDialog(this,"This field must be empty as it is auto-generated. Please clear this field.","Invalid ID Input",JOptionPane.ERROR_MESSAGE);
                if(!s1.isEmpty()){
                txt_ID.requestFocus(); 
                txt_ID.selectAll();
                }
                else{
                    txtDate.requestFocus(); 
                    txtDate.selectAll(); 
                }
                return;
            }
            
            /*checking for empty fields*/
            if(s2.equals("--Select Supplier ID--") || s3.isEmpty() || s5.equals("--Select Branch ID--") || s4.isEmpty()){
                JOptionPane.showMessageDialog(this,"Please fill all required fields","Validation Error",JOptionPane.ERROR_MESSAGE);
                if(s2.equals("--Select Supplier ID--")){
                    comboSupplier_id.requestFocus();
                }
                else if(s5.equals("--Select Branch ID--")){
                    comboBranch_id.requestFocus();
                }
               
                else if(s3.isEmpty()){
                    txtExpense_type.requestFocus();
                }
                
                else if(s4.isEmpty()){
                    txtAmount.requestFocus();
                }
                
                return;
            }
            
            /*check number is positive*/
         
            if (s3.length() > 15) {
                JOptionPane.showMessageDialog(this, "Expenses Type cannot exceed 15 characters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                txtExpense_type.requestFocus();
                txtExpense_type.selectAll();
                return;
            }
           
            if(!s3.matches("^[a-zA-Z\\s\\-\\'\\,]+$")){
                JOptionPane.showMessageDialog(this, "Expenses Type cannot contain integers","Invalid Location Format", 
                JOptionPane.ERROR_MESSAGE);
                txtExpense_type.requestFocus();
                txtExpense_type.selectAll();
                return;
            }
    
            Connection con = null;
            PreparedStatement pstmt = null;
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
               query = "INSERT INTO expenses (Supplier_ID, Branch_ID, Type_of_expense, Amount) VALUES (?, ?, ?, ?)";
                pstmt = con.prepareStatement(query);
                
                
                pstmt.setString(1, s2);
                pstmt.setString(2, s5);
                pstmt.setString(3, s3);
                pstmt.setString(4, s4);
               
                /*validate saving*/
                int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to Save this record","Confirm Save",JOptionPane.YES_NO_OPTION);
        
                if (confirm != JOptionPane.YES_OPTION) {
                    return; // User cancelled1
                }
                
                int rowsaffected = pstmt.executeUpdate();
                if(rowsaffected > 0){
                    JOptionPane.showMessageDialog(null,"Record Saved Successfully");
                    clearFields();

                    comboSupplier_id.requestFocus();
                }
                else {
                    JOptionPane.showMessageDialog(this, "Failed to save record","Error",JOptionPane.ERROR_MESSAGE);
                }
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(cs, user, password);
            query = "SELECT * FROM expenses ORDER By ID ASC LIMIT 1";
            st = con.createStatement();

            rs = st.executeQuery(query);
            if (rs.next()){
                String foundID = rs.getString("ID");
                String Supplier_ID = rs.getString("Supplier_ID");
                String Branch_ID = rs.getString("Branch_ID");
                String Type_of_expense = rs.getString("Type_of_expense");
                String Amount = rs.getString("Amount");
                String Entry_Date = rs.getString("Entry_Date");

                //update the text fields
                txt_ID.setText(foundID);
                txtExpense_type.setText(Type_of_expense);
                comboSupplier_id.setSelectedItem(Supplier_ID);
                txtAmount.setText(Amount);
                comboBranch_id.setSelectedItem(Branch_ID);
                txtDate.setText(Entry_Date);
                
                JOptionPane.showMessageDialog(null,"First Record Retrieved Successfully");
            }
            else {
                JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
            }

        }
        catch (SQLException ex){
            ex.printStackTrace();
        }
        catch (ClassNotFoundException e){
            e.printStackTrace();
        }
        finally {
            try{
                if (st != null){
                    st.close();
                }
                if (con != null){
                    con.close();
                }
            }
            catch (SQLException ex){
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(cs, user, password);
            query = "SELECT * FROM expenses ORDER By ID DESC LIMIT 1";
            st = con.createStatement();

            rs = st.executeQuery(query);
            if (rs.next()){
                 String foundID = rs.getString("ID");
                String Supplier_ID = rs.getString("Supplier_ID");
                String Branch_ID = rs.getString("Branch_ID");
                String Type_of_expense = rs.getString("Type_of_expense");
                String Amount = rs.getString("Amount");
                String Entry_Date = rs.getString("Entry_Date");

                //update the text fields
                txt_ID.setText(foundID);
                txtExpense_type.setText(Type_of_expense);
                comboSupplier_id.setSelectedItem(Supplier_ID);
                txtAmount.setText(Amount);
                comboBranch_id.setSelectedItem(Branch_ID);
                txtDate.setText(Entry_Date);
                
                JOptionPane.showMessageDialog(null,"Last Record Retrieved Successfully");
            }
            else {
                JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
            }

        }
        catch (SQLException ex){
            ex.printStackTrace();
        }
        catch (ClassNotFoundException e){
            e.printStackTrace();
        }
        finally {
            try{
                if (st != null){
                    st.close();
                }
                if (con != null){
                    con.close();
                }
            }
            catch (SQLException ex){
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String s1 = txt_ID.getText();
        if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a record or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;

        }
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(cs, user, password);
            query = "SELECT * FROM expenses WHERE ID > ? ORDER By ID ASC LIMIT 1";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, s1);

            rs = pst.executeQuery();
            if (rs.next()){
                 String foundID = rs.getString("ID");
                String Supplier_ID = rs.getString("Supplier_ID");
                String Branch_ID = rs.getString("Branch_ID");
                String Type_of_expense = rs.getString("Type_of_expense");
                String Amount = rs.getString("Amount");
                String Entry_Date = rs.getString("Entry_Date");

                //update the text fields
                txt_ID.setText(foundID);
                txtExpense_type.setText(Type_of_expense);
                comboSupplier_id.setSelectedItem(Supplier_ID);
                txtAmount.setText(Amount);
                comboBranch_id.setSelectedItem(Branch_ID);
                txtDate.setText(Entry_Date);
                
            }
            else {
                JOptionPane.showMessageDialog(this, "This is the last record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);

            }
        }

        catch (SQLException ex){
            ex.printStackTrace();
        }
        catch (ClassNotFoundException e){
            e.printStackTrace();
        }
        finally {
            try{
                if (st != null){
                    st.close();
                }
                if (con != null){
                    con.close();
                }
            }
            catch (SQLException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        String s1 = txt_ID.getText();
        if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a record or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;

        }
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(cs, user, password);
            query = "SELECT * FROM expenses WHERE ID < ? ORDER By ID DESC LIMIT 1";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, s1);

            rs = pst.executeQuery();
            if (rs.next()){
                String foundID = rs.getString("ID");
                String Supplier_ID = rs.getString("Supplier_ID");
                String Branch_ID = rs.getString("Branch_ID");
                String Type_of_expense = rs.getString("Type_of_expense");
                String Amount = rs.getString("Amount");
                String Entry_Date = rs.getString("Entry_Date");

                //update the text fields
                txt_ID.setText(foundID);
                txtExpense_type.setText(Type_of_expense);
                comboSupplier_id.setSelectedItem(Supplier_ID);
                txtAmount.setText(Amount);
                comboBranch_id.setSelectedItem(Branch_ID);
                txtDate.setText(Entry_Date);
                
            }
            else {
                JOptionPane.showMessageDialog(this, "This is the first record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);

            }
        }

        catch (SQLException ex){
            ex.printStackTrace();
        }
        catch (ClassNotFoundException e){
            e.printStackTrace();
        }
        finally {
            try{
                if (st != null){
                    st.close();
                }
                if (con != null){
                    con.close();
                }
            }
            catch (SQLException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnFirst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirst1ActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(cs, user, password);
            query = "SELECT * FROM expenses ORDER By ID ASC LIMIT 1";
            st = con.createStatement();

            rs = st.executeQuery(query);
            if (rs.next()){
                 String foundID = rs.getString("ID");
                String Supplier_ID = rs.getString("Supplier_ID");
                String Branch_ID = rs.getString("Branch_ID");
                String Type_of_expense = rs.getString("Type_of_expense");
                String Amount = rs.getString("Amount");
                String Entry_Date = rs.getString("Entry_Date");

                //update the text fields
                txt_ID.setText(foundID);
                txtExpense_type.setText(Type_of_expense);
                comboSupplier_id.setSelectedItem(Supplier_ID);
                txtAmount.setText(Amount);
                comboBranch_id.setSelectedItem(Branch_ID);
                txtDate.setText(Entry_Date);
                
                JOptionPane.showMessageDialog(null,"First Record Retrieved Successfully");
            }
            else {
                JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
            }

        }
        catch (SQLException ex){
            ex.printStackTrace();
        }
        catch (ClassNotFoundException e){
            e.printStackTrace();
        }
        finally {
            try{
                if (st != null){
                    st.close();
                }
                if (con != null){
                    con.close();
                }
            }
            catch (SQLException ex){
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnFirst1ActionPerformed

    private void btnLast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLast1ActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(cs, user, password);
            query = "SELECT * FROM expenses ORDER By ID DESC LIMIT 1";
            st = con.createStatement();

            rs = st.executeQuery(query);
            if (rs.next()){
                 String foundID = rs.getString("ID");
                String Supplier_ID = rs.getString("Supplier_ID");
                String Branch_ID = rs.getString("Branch_ID");
                String Type_of_expense = rs.getString("Type_of_expense");
                String Amount = rs.getString("Amount");
                String Entry_Date = rs.getString("Entry_Date");

                //update the text fields
                txt_ID.setText(foundID);
                txtExpense_type.setText(Type_of_expense);
                comboSupplier_id.setSelectedItem(Supplier_ID);
                txtAmount.setText(Amount);
                comboBranch_id.setSelectedItem(Branch_ID);
                txtDate.setText(Entry_Date);
                
                JOptionPane.showMessageDialog(null,"Last Record Retrieved Successfully");
            }
            else {
                JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
            }

        }
        catch (SQLException ex){
            ex.printStackTrace();
        }
        catch (ClassNotFoundException e){
            e.printStackTrace();
        }
        finally {
            try{
                if (st != null){
                    st.close();
                }
                if (con != null){
                    con.close();
                }
            }
            catch (SQLException ex){
                ex.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnLast1ActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        String s1 = txt_ID.getText();
        if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a record or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;

        }
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(cs, user, password);
            query = "SELECT * FROM expenses WHERE ID > ? ORDER By ID ASC LIMIT 1";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, s1);

            rs = pst.executeQuery();
            if (rs.next()){
                 String foundID = rs.getString("ID");
                String Supplier_ID = rs.getString("Supplier_ID");
                String Branch_ID = rs.getString("Branch_ID");
                String Type_of_expense = rs.getString("Type_of_expense");
                String Amount = rs.getString("Amount");
                String Entry_Date = rs.getString("Entry_Date");

                //update the text fields
                txt_ID.setText(foundID);
                txtExpense_type.setText(Type_of_expense);
                comboSupplier_id.setSelectedItem(Supplier_ID);
                txtAmount.setText(Amount);
                comboBranch_id.setSelectedItem(Branch_ID);
                txtDate.setText(Entry_Date);
                
            }
            else {
                JOptionPane.showMessageDialog(this, "This is the last record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);

            }
        }

        catch (SQLException ex){
            ex.printStackTrace();
        }
        catch (ClassNotFoundException e){
            e.printStackTrace();
        }
        finally {
            try{
                if (st != null){
                    st.close();
                }
                if (con != null){
                    con.close();
                }
            }
            catch (SQLException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnPrevious1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious1ActionPerformed
        String s1 = txt_ID.getText();
        if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a record or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;

        }
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(cs, user, password);
            query = "SELECT * FROM expenses WHERE ID < ? ORDER By ID DESC LIMIT 1";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, s1);

            rs = pst.executeQuery();
            if (rs.next()){
                String foundID = rs.getString("ID");
                String Supplier_ID = rs.getString("Supplier_ID");
                String Branch_ID = rs.getString("Branch_ID");
                String Type_of_expense = rs.getString("Type_of_expense");
                String Amount = rs.getString("Amount");
                String Entry_Date = rs.getString("Entry_Date");

                //update the text fields
                txt_ID.setText(foundID);
                txtExpense_type.setText(Type_of_expense);
                comboSupplier_id.setSelectedItem(Supplier_ID);
                txtAmount.setText(Amount);
                comboBranch_id.setSelectedItem(Branch_ID);
                txtDate.setText(Entry_Date);
                
            }
            else {
                JOptionPane.showMessageDialog(this, "This is the first record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);

            }
        }

        catch (SQLException ex){
            ex.printStackTrace();
        }
        catch (ClassNotFoundException e){
            e.printStackTrace();
        }
        finally {
            try{
                if (st != null){
                    st.close();
                }
                if (con != null){
                    con.close();
                }
            }
            catch (SQLException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnPrevious1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        else {
            this.dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_form().setVisible(true);
            }
        });
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Expenses_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Expenses_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Expenses_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Expenses_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Expenses_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnFirst1;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnLast1;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnPrevious1;
    private javax.swing.JComboBox<String> comboBranch_id;
    private javax.swing.JComboBox<String> comboSupplier_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtExpense_type;
    private javax.swing.JTextField txt_ID;
    // End of variables declaration//GEN-END:variables

    private void populatecombosid() {
        Connection localCon = null;
    Statement localSt = null;
    ResultSet localRs = null;
     
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        localCon = DriverManager.getConnection(cs, user, password);
        localSt = localCon.createStatement();
        
        // Populate Poultry ID combo box
        query = "SELECT ID FROM supplier";
        localRs = localSt.executeQuery(query);
        
        DefaultComboBoxModel<String> poultryModel = new DefaultComboBoxModel<>();
        poultryModel.addElement("--Select Supplier ID--");
        while (localRs.next()) {
            poultryModel.addElement(localRs.getString("ID"));
        }
        comboSupplier_id.setModel(poultryModel);
        
        // Close the first result set
        localRs.close();
        
        // Populate Reported By combo box with User IDs
        query = "SELECT ID FROM branches";
        localRs = localSt.executeQuery(query);
        
        DefaultComboBoxModel<String> userModel = new DefaultComboBoxModel<>();
        userModel.addElement("--Select Branch ID--");
        while (localRs.next()) {
            userModel.addElement(localRs.getString("ID"));
        }
        comboBranch_id.setModel(userModel);
        
    } catch (SQLException | ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(this, "Error loading data: " + ex.getMessage(), 
            "Database Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    } finally {
        try {
            if (localRs != null) localRs.close();
            if (localSt != null) localSt.close();
            if (localCon != null) localCon.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    }

    private void clearFields() {
        txt_ID.setText("");
        txtExpense_type.setText("");
        comboSupplier_id.setSelectedItem("--Select Supplier ID--");
        txtAmount.setText("");
        comboBranch_id.setSelectedItem("--Select Branch ID--");
        txtDate.setText("");
    }
}
