/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poultry_farm;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HOOKE GEN
 */
public class Feed_consumption_form extends javax.swing.JFrame {
    
    private String callerRole;
    Connection con;
    Statement st;
    String cs;
    
    String user;
    String password;
    
    String query;
    ResultSet rs;
    public Feed_consumption_form(String callerRole) {
        this.callerRole = callerRole;
        con = null;
        st = null;
        cs = "jdbc:mysql://localhost:3306/poultry_farm";
        user = "root";
        password = "henry";
        setTitle("Feed Consumption");
        initComponents();
        populateFeed_mixtureCombo();
        comboFeed_mixture_Id.requestFocus();
        populateFeed_mixtureCombo();
        btnSave.setEnabled(false);
    
    // Add action listener to combo box - ADD THESE LINES
    comboFeed_mixture_Id.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            comboFeed_mixture_IdActionPerformed(evt);
        }
    });
    
    comboFeed_mixture_Id.requestFocus();
    }

    private Feed_consumption_form() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtQuantity_in_stock = new javax.swing.JTextField();
        txtQuantity_given = new javax.swing.JTextField();
        txtBalance_in_Stock = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txt_ID = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        comboFeed_mixture_Id = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 9, -1, -1));

        jLabel2.setText("Feed Mixture ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 40, -1, -1));

        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 68, -1, -1));

        jLabel4.setText("Quantity in Stock");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 102, -1, -1));

        jLabel5.setText("Quantity Given");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 136, -1, -1));

        jLabel6.setText("Balance in Stock");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 170, -1, -1));
        getContentPane().add(txtQuantity_in_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 99, 287, -1));
        getContentPane().add(txtQuantity_given, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 133, 287, -1));
        getContentPane().add(txtBalance_in_Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 167, 287, -1));

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 65, 287, -1));
        getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 6, 287, -1));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 207, -1, -1));

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 207, -1, -1));

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 207, -1, -1));

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 207, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 207, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 207, -1, -1));

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        getContentPane().add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 207, -1, -1));

        comboFeed_mixture_Id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboFeed_mixture_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 37, 287, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOOKE GEN\\Documents\\NetBeansProjects\\Poultry_Farm\\poultry_pictures\\eggs_new.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
         String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a record or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM feed_consumption  WHERE ID < ? ORDER By ID DESC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Feed_Mixture_ID = rs.getString("Feed_Mixture_ID");
                    String Entry_Date = rs.getString("Entry_Date");
                    String Total_Quantity = rs.getString("Total_Quantity");
                    String Quantity_Consumed = rs.getString("Quantity_Consumed");
                    String Balance_in_stock = rs.getString("Balance_in_stock");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    comboFeed_mixture_Id.setSelectedItem(Feed_Mixture_ID);
                    txtDate.setText(Entry_Date);
                    txtQuantity_in_stock.setText(Total_Quantity);
                    txtQuantity_given.setText(Quantity_Consumed);
                    txtBalance_in_Stock.setText(Balance_in_stock);
}
                    else {
                    JOptionPane.showMessageDialog(this, "This is the first record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
                
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        else {
            this.dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            if ("admin".equals(callerRole)) {
                new Admin_form().setVisible(true); // Open Admin_form
            } else if ("worker".equals(callerRole)) {
                new Worker_form().setVisible(true); // Open Worker_form
            } else {
                // Fallback in case callerRole is not set (optional)
                JOptionPane.showMessageDialog(null, "Unknown caller role. Returning to Worker form.", "Warning", JOptionPane.WARNING_MESSAGE);
                new Worker_form().setVisible(true);
            }
        }
    });
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
         String s1 = txt_ID.getText();
         
         //check if ID is entered
         if ( s1.isEmpty()){
             JOptionPane.showMessageDialog(this, "Please enter the reord ID to search", "Error", JOptionPane.ERROR_MESSAGE);
             txt_ID.requestFocus();
             return;
         }
         
         /*check if positive integer is entered*/
        if (!s1.matches("\\d+")) {
            JOptionPane.showMessageDialog(this,"ID must be a positive whole number","Invalid ID Format",JOptionPane.ERROR_MESSAGE);
            txt_ID.requestFocus();
            txt_ID.selectAll();
            return;
    }
            
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM feed_consumption WHERE ID = ?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1,s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Feed_Mixture_ID = rs.getString("Feed_Mixture_ID");
                    String Entry_Date = rs.getString("Entry_Date");
                    String Total_Quantity = rs.getString("Total_Quantity");
                    String Quantity_Consumed = rs.getString("Quantity_Consumed");
                    String Balance_in_stock = rs.getString("Balance_in_stock");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    comboFeed_mixture_Id.setSelectedItem(Feed_Mixture_ID);
                    txtDate.setText(Entry_Date);
                    txtQuantity_in_stock.setText(Total_Quantity);
                    txtQuantity_given.setText(Quantity_Consumed);
                    txtBalance_in_Stock.setText(Balance_in_stock);
                    JOptionPane.showMessageDialog(null,"Record Retrieved Successfully");
                }
                //no record found
                else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Not Found", JOptionPane.WARNING_MESSAGE);
                    clearFields();
                    txt_ID.requestFocus();
                }
                
}
             catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM feed_consumption ORDER By ID ASC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Feed_Mixture_ID = rs.getString("Feed_Mixture_ID");
                    String Entry_Date = rs.getString("Entry_Date");
                    String Total_Quantity = rs.getString("Total_Quantity");
                    String Quantity_Consumed = rs.getString("Quantity_Consumed");
                    String Balance_in_stock = rs.getString("Balance_in_stock");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    comboFeed_mixture_Id.setSelectedItem(Feed_Mixture_ID);
                    txtDate.setText(Entry_Date);
                    txtQuantity_in_stock.setText(Total_Quantity);
                    txtQuantity_given.setText(Quantity_Consumed);
                    txtBalance_in_Stock.setText(Balance_in_stock);
                 JOptionPane.showMessageDialog(null,"First Record Retrieved Successfully");
                }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
        }
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
       try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM feed_consumption ORDER By ID DESC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Feed_Mixture_ID = rs.getString("Feed_Mixture_ID");
                    String Entry_Date = rs.getString("Entry_Date");
                    String Total_Quantity = rs.getString("Total_Quantity");
                    String Quantity_Consumed = rs.getString("Quantity_Consumed");
                    String Balance_in_stock = rs.getString("Balance_in_stock");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    comboFeed_mixture_Id.setSelectedItem(Feed_Mixture_ID);
                    txtDate.setText(Entry_Date);
                    txtQuantity_in_stock.setText(Total_Quantity);
                    txtQuantity_given.setText(Quantity_Consumed);
                    txtBalance_in_Stock.setText(Balance_in_stock);
                 JOptionPane.showMessageDialog(null,"Last Record Retrieved Successfully");
                }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
        }
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a record or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM feed_consumption  WHERE ID > ? ORDER By ID ASC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Feed_Mixture_ID = rs.getString("Feed_Mixture_ID");
                    String Entry_Date = rs.getString("Entry_Date");
                    String Total_Quantity = rs.getString("Total_Quantity");
                    String Quantity_Consumed = rs.getString("Quantity_Consumed");
                    String Balance_in_stock = rs.getString("Balance_in_stock");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    comboFeed_mixture_Id.setSelectedItem(Feed_Mixture_ID);
                    txtDate.setText(Entry_Date);
                    txtQuantity_in_stock.setText(Total_Quantity);
                    txtQuantity_given.setText(Quantity_Consumed);
                    txtBalance_in_Stock.setText(Balance_in_stock);
}
                    else {
                    JOptionPane.showMessageDialog(this, "This is the last record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
                
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            String s1 = txt_ID.getText();   
            String s2 = txtDate.getText();
            String s3 = (String)comboFeed_mixture_Id.getSelectedItem();
            String s4 = txtQuantity_in_stock.getText();
            String s5 = txtQuantity_given.getText();
            String s6 = txtBalance_in_Stock.getText();
            
            /*checking if there is data entered in the ID field*/
            if (!s1.isEmpty() || !s2.isEmpty()|| !s6.isEmpty()) {
                JOptionPane.showMessageDialog(this,"This field must be empty as it is auto-generated. Please clear this field.","Invalid Input",JOptionPane.ERROR_MESSAGE);
                if(!s1.isEmpty()){
                   txt_ID.requestFocus(); 
                   txt_ID.selectAll();
                }
                else if(!s2.isEmpty()){
                    txtDate.requestFocus();
                    txtDate.selectAll();
                 }
                else{
                    txtBalance_in_Stock.requestFocus();
                    txtBalance_in_Stock.selectAll();
                }
                return;
            }
            if (s4 == null || s4.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Quantity in stock is not available. Please select a valid Feed Mixture ID.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            comboFeed_mixture_Id.requestFocus();
            return;
        }
            
            /*checking for empty fields*/
            if(s3 == null|| s5.isEmpty()|| s3.equals("--Select the feed mixture ID---")){
                JOptionPane.showMessageDialog(this,"Please fill all required fields","Validation Error",JOptionPane.ERROR_MESSAGE);
                if(s3 == null){
                    comboFeed_mixture_Id.requestFocus();
                }
                else if(s5.isEmpty()){
                    txtQuantity_given.requestFocus();
                }
                else if(s3.equals("--Select the feed mixture ID---")){
                    comboFeed_mixture_Id.requestFocus();
                }
                
                return;
            }
            
            /*check number is positive*/
            if(!s5.matches("\\d+")){
                JOptionPane.showMessageDialog(this,"Quantitive must be a positive whole number", "Invalid Data Type",JOptionPane.ERROR_MESSAGE);
                txtQuantity_given.requestFocus();
                txtQuantity_given.selectAll();
                return;
            }
            
            double quantity_in_stock;
            double quantity_given;
            try {
                quantity_in_stock = Double.parseDouble(s4);
                quantity_given = Double.parseDouble(s5);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid number format for quantities", "Invalid Data Type", JOptionPane.ERROR_MESSAGE);
                txtQuantity_given.requestFocus();
                txtQuantity_given.selectAll();
                return;
            }
            
            if(quantity_given < 0){
                JOptionPane.showMessageDialog(this,"Quantity given cannot be negative","Invalid Value",JOptionPane.ERROR_MESSAGE);
                txtQuantity_given.requestFocus();
                txtQuantity_given.selectAll();
                return;
            }
            if(quantity_in_stock <= 0){
                JOptionPane.showMessageDialog(this, "Feeds are over  please mix","Error Message",JOptionPane.ERROR_MESSAGE);
                return;
            }
            /*calculate the total*/
            double balance_in_stock = quantity_in_stock - quantity_given;
            txtBalance_in_Stock.setText(String.format("%.2f", balance_in_stock));
            
            Connection con = null;
            PreparedStatement pstmt = null;
            
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
               query = "INSERT INTO feed_consumption (Feed_Mixture_ID, Total_Quantity, Quantity_Consumed, Balance_in_stock) VALUES (?, ?, ?, ?)";
                pstmt = con.prepareStatement(query);
                pstmt.setString(1, s3);
                pstmt.setDouble(2, quantity_in_stock);
                pstmt.setDouble(3, quantity_given);
                pstmt.setDouble(4, balance_in_stock);
                
                /*validate saving*/
                int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to Save this record","Confirm Save",JOptionPane.YES_NO_OPTION);
        
                if (confirm != JOptionPane.YES_OPTION) {
                    return; // User cancelled1
                }
                
                int rowsaffected = pstmt.executeUpdate();
                if(rowsaffected > 0){
                    JOptionPane.showMessageDialog(null,"Record Saved Successfully");
                    clearFields();
                    if (s3 != null && !s3.equals("--Select the ID of feed mixture---")) {
                         populateQuantityInStock(s3);
            }
            
                populateFeed_mixtureCombo(); // Refresh combo box
                comboFeed_mixture_Id.requestFocus();
                    
                }
                
                else {
                    JOptionPane.showMessageDialog(this, "Failed to save record","Error",JOptionPane.ERROR_MESSAGE);
                }
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feed_consumption_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feed_consumption_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feed_consumption_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feed_consumption_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feed_consumption_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboFeed_mixture_Id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtBalance_in_Stock;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtQuantity_given;
    private javax.swing.JTextField txtQuantity_in_stock;
    private javax.swing.JTextField txt_ID;
    // End of variables declaration//GEN-END:variables

private void populateFeed_mixtureCombo() {
         Connection localCon = null;
        Statement localSt = null;
        ResultSet localRs = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            localCon = DriverManager.getConnection(cs, user, password);
            localSt = localCon.createStatement();
            query = "SELECT ID FROM feed_mixture ORDER BY ID DESC LIMIT 1"; // Adjust table/column name as needed
            localRs = localSt.executeQuery(query);
            
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("--Select the ID of feed mixture---");
            while (localRs.next()) {
                model.addElement(localRs.getString("ID"));
            }
            comboFeed_mixture_Id.setModel(model);
            
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error loading users: " + ex.getMessage(), 
                "Database Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } finally {
            try {
                if (localRs != null) localRs.close();
                if (localSt != null) localSt.close();
                if (localCon != null) localCon.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

    private void clearFields() {
        txt_ID.setText("");
        comboFeed_mixture_Id.setSelectedItem("--Select the feed mixture ID---");
        txtDate.setText("");
        txtQuantity_in_stock.setText("");
        txtQuantity_given.setText("");
        txtBalance_in_Stock.setText("");
        txtQuantity_in_stock.setBackground(Color.WHITE);
    }
    private void populateQuantityInStock(String feedMixtureId) {
        Connection localCon = null;
        PreparedStatement pst = null;
        ResultSet localRs = null;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            localCon = DriverManager.getConnection(cs, user, password);

            // Get the last balance from feed_consumption table for this feed mixture
            String queryBalance = "SELECT Balance_in_stock FROM feed_consumption WHERE Feed_Mixture_ID = ? ORDER BY ID DESC LIMIT 1";
            pst = localCon.prepareStatement(queryBalance);
            pst.setString(1, feedMixtureId);
            localRs = pst.executeQuery();

            double currentStock = 0;

            if (localRs.next()) {
                // Use the last balance as current stock
                currentStock = localRs.getDouble("Balance_in_stock");
            } else {
                // If no consumption records exist, get the initial quantity from feed_mixture table
                String queryInitial = "SELECT Total_Quantity FROM feed_mixture WHERE ID = ?";
                pst = localCon.prepareStatement(queryInitial);
                pst.setString(1, feedMixtureId);
                localRs = pst.executeQuery();

                if (localRs.next()) {
                    currentStock = localRs.getDouble("Total_Quantity");
                }
                else {
                // No feed mixture found
                currentStock = 0;
                JOptionPane.showMessageDialog(this, "No feed mixture found for ID: " + feedMixtureId, "Error", JOptionPane.WARNING_MESSAGE);
                btnSave.setEnabled(false);
                txtQuantity_in_stock.setText("0");
                txtQuantity_in_stock.setBackground(Color.LIGHT_GRAY);
                return;
            }
            }

            // Update the quantity in stock field
            txtQuantity_in_stock.setText(String.format("%.2f", currentStock));
             btnSave.setEnabled(true);
            txtQuantity_in_stock.setBackground(Color.WHITE);
        }
        catch (SQLException | ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(this, "Error calculating stock: " + ex.getMessage(),"Database Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
        txtQuantity_in_stock.setText("0");
        btnSave.setEnabled(false);
        txtQuantity_in_stock.setBackground(Color.LIGHT_GRAY);
    } 
        finally {
        try {
            if (localRs != null) localRs.close();
            if (pst != null) pst.close();
            if (localCon != null) localCon.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}
    private void comboFeed_mixture_IdActionPerformed(java.awt.event.ActionEvent evt) {
    String selectedFeedId = (String) comboFeed_mixture_Id.getSelectedItem();
    
    // Check if a valid feed mixture ID is selected (not the prompt)
    if (selectedFeedId != null && !selectedFeedId.equals("--Select the ID of feed mixture---")) {
        populateQuantityInStock(selectedFeedId);
        txtQuantity_given.requestFocus();
    } else {
        // Clear fields if prompt is selected
        txtQuantity_in_stock.setText("");
        txtDate.setText("");
        txtQuantity_given.setText("");
        txtBalance_in_Stock.setText("");
    }
}

}
