/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poultry_farm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HOOKE GEN
 */
public class Financial_transaction extends javax.swing.JFrame {
    Connection con;
    Statement st;
    String cs;
    
    String user;
    String password;
    
    String query;
    ResultSet rs;
    
    public Financial_transaction() {
        
        setTitle("Financial Transaction");
        initComponents();
        con = null;
        st = null;
        cs = "jdbc:mysql://localhost:3306/poultry_farm";
        user = "root";
        password = "henry";
        populateperfromedbyfield();
        comboTransaction_type.requestFocus();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        comboTransaction_type = new javax.swing.JComboBox<>();
        comboCategory = new javax.swing.JComboBox<>();
        txtDescription = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        comboPayment_method = new javax.swing.JComboBox<>();
        txtReference = new javax.swing.JTextField();
        txtNotes = new javax.swing.JTextField();
        btnPrevious = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        comboRecorded_by = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 9, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Date");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 37, 40, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 286, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Transaction Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 65, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Category");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 93, 70, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Description");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 121, 80, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Amount");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 149, 60, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Payment Method");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 177, 100, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Reference No.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 205, 90, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Recorded By");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 233, 90, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Notes");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 261, 40, -1));
        getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 6, 238, -1));
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 34, 238, -1));

        comboTransaction_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select transaction type--", "INCOME", "EXPENSE", " " }));
        getContentPane().add(comboTransaction_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 62, 238, -1));

        comboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select category--", "FEED", "EQUIPMENT", "LABOR", "UTILITIES", "SALES", "MAINTENANCE", "VETERINARY", "TRANSPORTATION", "SUPPLIES", " ", " ", " " }));
        getContentPane().add(comboCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 238, -1));
        getContentPane().add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 118, 238, -1));
        getContentPane().add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 146, 238, -1));

        comboPayment_method.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select payment method--", "CASH", "BANK_TRANSFER", "MOBILE_MONEY", "CHEQUE" }));
        getContentPane().add(comboPayment_method, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 174, 238, -1));
        getContentPane().add(txtReference, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 202, 238, -1));

        txtNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotesActionPerformed(evt);
            }
        });
        getContentPane().add(txtNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 258, 472, -1));

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 292, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 292, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 292, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 292, -1, -1));

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 292, -1, -1));

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 292, -1, -1));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 292, -1, -1));

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        getContentPane().add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 292, -1, -1));

        comboRecorded_by.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboRecorded_by, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 238, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOOKE GEN\\Documents\\NetBeansProjects\\Poultry_Farm\\poultry_pictures\\financial_transact.jpg")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotesActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
         String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a Branch or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM financial_transaction WHERE ID < ? ORDER By ID DESC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                     //record found
                    String foundID = rs.getString("ID");
                    String Transaction_date = rs.getString("Transaction_date");
                    String Type = rs.getString("Type");
                    String Category = rs.getString("Category");
                    String Description = rs.getString("Description");
                    String Amount = rs.getString("Amount");
                    String  Payment_method = rs.getString("Payment_method");
                    String Reference_number = rs.getString("Reference_number");
                    String Recorded_by = rs.getString("Recorded_by");
                    String Notes = rs.getString("Notes");
                    
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Transaction_date);
                    comboTransaction_type.setSelectedItem(Type);
                    comboCategory.setSelectedItem(Category);
                    txtDescription.setText(Description);
                    txtAmount.setText(Amount);
                    comboPayment_method.setSelectedItem(Payment_method);
                    txtReference.setText(Reference_number);
                    comboRecorded_by.setSelectedItem(Recorded_by);
                    txtNotes.setText(Notes);
                     }
                else {
                    JOptionPane.showMessageDialog(this, "This is the first record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                
}
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
                  }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String s1 = txt_ID.getText();
         
         //check if ID is entered
         if ( s1.isEmpty()){
             JOptionPane.showMessageDialog(this, "Please enter the reord ID to search", "Error", JOptionPane.ERROR_MESSAGE);
             txt_ID.requestFocus();
             return;
         }
         
         /*check if positive integer is entered*/
        if (!s1.matches("\\d+")) {
            JOptionPane.showMessageDialog(this,"ID must be a positive whole number","Invalid ID Format",JOptionPane.ERROR_MESSAGE);
            txt_ID.requestFocus();
            txt_ID.selectAll();
            return;
    }
            
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM financial_transaction WHERE ID = ?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1,s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Transaction_date = rs.getString("Transaction_date");
                    String Type = rs.getString("Type");
                    String Category = rs.getString("Category");
                    String Description = rs.getString("Description");
                    String Amount = rs.getString("Amount");
                    String  Payment_method = rs.getString("Payment_method");
                    String Reference_number = rs.getString("Reference_number");
                    String Recorded_by = rs.getString("Recorded_by");
                    String Notes = rs.getString("Notes");
                    
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Transaction_date);
                    comboTransaction_type.setSelectedItem(Type);
                    comboCategory.setSelectedItem(Category);
                    txtDescription.setText(Description);
                    txtAmount.setText(Amount);
                    comboPayment_method.setSelectedItem(Payment_method);
                    txtReference.setText(Reference_number);
                    comboRecorded_by.setSelectedItem(Recorded_by);
                    txtNotes.setText(Notes);
                    JOptionPane.showMessageDialog(null,"Record Retrieved Successfully");
                }
                //no record found
                else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Not Found", JOptionPane.WARNING_MESSAGE);
                    clearFields();
                    txt_ID.requestFocus();
                }
                
}
             catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM financial_transaction ORDER By ID ASC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Transaction_date = rs.getString("Transaction_date");
                    String Type = rs.getString("Type");
                    String Category = rs.getString("Category");
                    String Description = rs.getString("Description");
                    String Amount = rs.getString("Amount");
                    String  Payment_method = rs.getString("Payment_method");
                    String Reference_number = rs.getString("Reference_number");
                    String Recorded_by = rs.getString("Recorded_by");
                    String Notes = rs.getString("Notes");
                    
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Transaction_date);
                    comboTransaction_type.setSelectedItem(Type);
                    comboCategory.setSelectedItem(Category);
                    txtDescription.setText(Description);
                    txtAmount.setText(Amount);
                    comboPayment_method.setSelectedItem(Payment_method);
                    txtReference.setText(Reference_number);
                    comboRecorded_by.setSelectedItem(Recorded_by);
                    txtNotes.setText(Notes);
                 JOptionPane.showMessageDialog(null,"First Record Retrieved Successfully");
                     }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }

                }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM financial_transaction ORDER By ID DESC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                     //record found
                    String foundID = rs.getString("ID");
                    String Transaction_date = rs.getString("Transaction_date");
                    String Type = rs.getString("Type");
                    String Category = rs.getString("Category");
                    String Description = rs.getString("Description");
                    String Amount = rs.getString("Amount");
                    String  Payment_method = rs.getString("Payment_method");
                    String Reference_number = rs.getString("Reference_number");
                    String Recorded_by = rs.getString("Recorded_by");
                    String Notes = rs.getString("Notes");
                    
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Transaction_date);
                    comboTransaction_type.setSelectedItem(Type);
                    comboCategory.setSelectedItem(Category);
                    txtDescription.setText(Description);
                    txtAmount.setText(Amount);
                    comboPayment_method.setSelectedItem(Payment_method);
                    txtReference.setText(Reference_number);
                    comboRecorded_by.setSelectedItem(Recorded_by);
                    txtNotes.setText(Notes);
                JOptionPane.showMessageDialog(null,"Last Record Retrieved Successfully");
                     }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }

                }   
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
       String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a Branch or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM financial_transaction WHERE ID > ? ORDER By ID ASC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                     //record found
                    String foundID = rs.getString("ID");
                    String Transaction_date = rs.getString("Transaction_date");
                    String Type = rs.getString("Type");
                    String Category = rs.getString("Category");
                    String Description = rs.getString("Description");
                    String Amount = rs.getString("Amount");
                    String  Payment_method = rs.getString("Payment_method");
                    String Reference_number = rs.getString("Reference_number");
                    String Recorded_by = rs.getString("Recorded_by");
                    String Notes = rs.getString("Notes");
                    
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Transaction_date);
                    comboTransaction_type.setSelectedItem(Type);
                    comboCategory.setSelectedItem(Category);
                    txtDescription.setText(Description);
                    txtAmount.setText(Amount);
                    comboPayment_method.setSelectedItem(Payment_method);
                    txtReference.setText(Reference_number);
                    comboRecorded_by.setSelectedItem(Recorded_by);
                    txtNotes.setText(Notes);
                     }
                else {
                    JOptionPane.showMessageDialog(this, "This is the last record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                
}
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
                  }
                
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String s1 = txt_ID.getText();
	if (s1.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please first find the record in the branches to delete", "Error", JOptionPane.ERROR_MESSAGE);
        txt_ID.requestFocus();
        return;
    }
        
			
	try {
            Class.forName("com.mysql.cj.jdbc.Driver"); // register the driver,
            con = DriverManager.getConnection(cs, user, password);
            String deletequery = "DELETE FROM financial_transaction WHERE ID = ?";
            PreparedStatement deleteStmt = con.prepareStatement(deletequery);
            deleteStmt.setString(1, s1);
            int confirm = JOptionPane.showConfirmDialog(this, "Are you Sure You want to Delete record with ID: " + s1 + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm != JOptionPane.YES_OPTION){
                return; //user cancelled
            }
            else{
                int rowsAffected = deleteStmt.executeUpdate();
             if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Record deleted successfully!");
                    // Clear fields after successful deletion
                    clearFields();
                }
            
            else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Error", JOptionPane.ERROR_MESSAGE);
            } 
        }
        }
        catch (SQLException ex) 
        {
            ex.printStackTrace();
	} 
        catch (ClassNotFoundException e) 
        {
            e.printStackTrace();
	} 
        finally {

            try {
		if (st != null) 
                {
                    st.close();
		}
		if (con != null) 
                {
                    con.close();
		}

            } 
            catch (SQLException ex) 
            {
                ex.printStackTrace();
            }
	}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            String s1 = txt_ID.getText();   
            String s2 = txtDate.getText();
            String s3 = (String) comboTransaction_type.getSelectedItem();
            String s4 = (String) comboCategory.getSelectedItem();
            String s5 = txtDescription.getText();
            String s6 = txtAmount.getText();
            String s7 = (String) comboPayment_method.getSelectedItem();
            String s8 = txtReference.getText();
            String s9 = (String) comboRecorded_by.getSelectedItem();
            String s10 = txtNotes.getText();
            
            /*checking if there is data entered in the ID field*/
            if (!s1.isEmpty() || !s2.isEmpty()) {
                JOptionPane.showMessageDialog(this,"This field must be empty as it is auto-generated. Please clear this field.","Invalid ID Input",JOptionPane.ERROR_MESSAGE);
                if(!s1.isEmpty()){
                txt_ID.requestFocus(); 
                txt_ID.selectAll();
                }
                else{
                    txtDate.requestFocus(); 
                    txtDate.selectAll();
                }
                return;
            }
            
            /*checking for empty fields*/
            if(s3.equals("--Select transaction type--") || s5.isEmpty() || s4.equals("--Select category--") || s6.isEmpty() || s7.equals("--Select payment method--") || s8.isEmpty() || s9.equals("--Select User ID---") || s10.isEmpty()){
                JOptionPane.showMessageDialog(this,"Please fill all required fields","Validation Error",JOptionPane.ERROR_MESSAGE);
                if(s3.equals("--Select transaction type--")){
                    comboTransaction_type.requestFocus();
                }
                else if(s4.equals("--Select category--")){
                    comboCategory.requestFocus();
                }
               
                else if(s7.equals("--Select payment method--")){
                    comboPayment_method.requestFocus();
                }
                else if(s5.isEmpty()){
                    txtDate.requestFocus();
                }
                else if(s6.isEmpty()){
                    txtAmount.requestFocus();
                }
                else if(s8.isEmpty()){
                    txtReference.requestFocus();
                }
                else if(s9.equals("--Select User ID---")){
                    comboRecorded_by.requestFocus();
                }
                else{
                    txtNotes.requestFocus();
                }
                return;
            }
            
            /*check number is positive*/
            if (!s6.matches("\\d+(\\.\\d{0,2})?")){
                JOptionPane.showMessageDialog(this,"Amount must be a positive number with upto 2 decimal places", "Invalid Data Type",JOptionPane.ERROR_MESSAGE);
                txtAmount.requestFocus();
                txtAmount.selectAll();
                return;
            }
            if (s5.length() > 100) {
                JOptionPane.showMessageDialog(this, "Description cannot exceed 100 characters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                txtDescription.requestFocus();
                txtDescription.selectAll();
                return;
            }
            if (s10.length() > 100) {
                JOptionPane.showMessageDialog(this, "Notes cannot exceed 100 characters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                txtNotes.requestFocus();
                txtNotes.selectAll();
                return;
            }
            if (s8.length() > 30) {
                JOptionPane.showMessageDialog(this, "Reference_no. cannot exceed 30 characters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                txtReference.requestFocus();
                txtReference.selectAll();
                return;
            }
                
            double amount = Double.parseDouble(s6);
            
            if(amount < 0){
                JOptionPane.showMessageDialog(this,"Age cannot be negative","Invalid Value",JOptionPane.ERROR_MESSAGE);
                txtAmount.requestFocus();
                txtAmount.selectAll();
                return;
            }
            
            
            Connection con = null;
            PreparedStatement pstmt = null;
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
               query = "INSERT INTO financial_transaction (Type, Category, Description,  Amount, Payment_method, Reference_number, Recorded_by, Notes) VALUES (?, ?, ?, ?,?,?,?,?)";
                pstmt = con.prepareStatement(query);
                
                
                pstmt.setString(1, s3);
                pstmt.setString(2, s4);
                pstmt.setString(3, s5);
                pstmt.setDouble(4, amount);
                pstmt.setString(5, s7);
                pstmt.setString(6,s8);
                pstmt.setString(7,s9);
                pstmt.setString(8,s10);
                
                /*validate saving*/
                int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to Save this record","Confirm Save",JOptionPane.YES_NO_OPTION);
        
                if (confirm != JOptionPane.YES_OPTION) {
                    return; // User cancelled1
                }
                
                int rowsaffected = pstmt.executeUpdate();
                if(rowsaffected > 0){
                    JOptionPane.showMessageDialog(null,"Record Saved Successfully");
                    clearFields();

                    comboTransaction_type.requestFocus();
                }
                else {
                    JOptionPane.showMessageDialog(this, "Failed to save record","Error",JOptionPane.ERROR_MESSAGE);
                }
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        else {
            this.dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_form().setVisible(true);
            }
        });
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Financial_transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Financial_transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Financial_transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Financial_transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Financial_transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboCategory;
    private javax.swing.JComboBox<String> comboPayment_method;
    private javax.swing.JComboBox<String> comboRecorded_by;
    private javax.swing.JComboBox<String> comboTransaction_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtNotes;
    private javax.swing.JTextField txtReference;
    private javax.swing.JTextField txt_ID;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        txt_ID.setText("");
        txtDate.setText("");
        comboTransaction_type.setSelectedItem("--Select transaction type--");
        comboCategory.setSelectedItem("--Select category--");
        txtDescription.setText("");
        txtAmount.setText("");
        comboPayment_method.setSelectedItem("--Select payment method--");
        txtReference.setText("");
        comboRecorded_by.setSelectedItem("--Select User ID---");
        txtNotes.setText("");
    }
    private void populateperfromedbyfield() {
         Connection localCon = null;
        Statement localSt = null;
        ResultSet localRs = null;
         
        try {
           Class.forName("com.mysql.cj.jdbc.Driver");
            localCon = DriverManager.getConnection(cs, user, password);
            localSt = localCon.createStatement();
            query = "SELECT User_ID FROM users";
        localRs = localSt.executeQuery(query);
        
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("--Select User ID---");
            while (localRs.next()) {
                model.addElement(localRs.getString("User_ID"));
            }
            comboRecorded_by.setModel(model);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error loading : " + ex.getMessage(), 
                "Database Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } finally {
            try {
                if (localRs != null) localRs.close();
                if (localSt != null) localSt.close();
                if (localCon != null) localCon.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

}
