/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poultry_farm;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HOOKE GEN
 */
public class Inventory_form extends javax.swing.JFrame {

    Connection con;
    Statement st;
    String cs;
    
    String user;
    String password;
    
    String query;
    ResultSet rs;
    public Inventory_form() {
        setTitle("INVENTORY FORM");
        initComponents();
        con = null;
        st = null;
        cs = "jdbc:mysql://localhost:3306/poultry_farm";
        user = "root";
        password = "henry";
        populatesupplierid();
        txtItem.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        txtItem = new javax.swing.JTextField();
        comboCategory = new javax.swing.JComboBox<>();
        txtQuantity = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        comboSupplier_id = new javax.swing.JComboBox<>();
        txtminimumstock = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 9, -1, -1));

        jLabel2.setText("Item ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 37, -1, -1));

        jLabel3.setText("Category");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 65, -1, -1));

        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 93, -1, -1));

        jLabel5.setText("Unit");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 121, -1, -1));

        jLabel6.setText("Date of Last Restock");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 149, -1, -1));

        jLabel7.setText("Supplier ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 177, -1, -1));

        jLabel8.setText("Minimum Stock Level");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 205, -1, -1));
        getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 6, 267, -1));
        getContentPane().add(txtItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 34, 267, -1));

        comboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select category--", "FEED", "MEDICAL", "EQUIPMENT", "CLEANING", "OTHER" }));
        getContentPane().add(comboCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 62, 267, -1));
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 90, 267, -1));
        getContentPane().add(txtUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 118, 267, -1));
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 146, 267, -1));

        comboSupplier_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboSupplier_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 174, 267, -1));
        getContentPane().add(txtminimumstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 202, 267, -1));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 269, -1, -1));

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 269, -1, -1));

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 269, -1, -1));

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 269, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 269, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 269, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 269, -1, -1));

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        getContentPane().add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 269, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOOKE GEN\\Documents\\NetBeansProjects\\Poultry_Farm\\poultry_pictures\\financial_transact.jpg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
         String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a Branch or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM inventory WHERE ID < ? ORDER By ID DESC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Item_Name = rs.getString("Item_Name");
                    String Category = rs.getString("Category");
                    String Quantity = rs.getString("Quantity");
                    String Unit = rs.getString("Unit");
                    String Last_restock_date = rs.getString("Last_restock_date");
                    String Supplier_ID = rs.getString("Supplier_ID");
                    String Minimum_stock_level = rs.getString("Minimum_stock_level");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Last_restock_date);
                    comboCategory.setSelectedItem(Category);
                    txtUnit.setText(Unit);
                    txtItem.setText(Item_Name);
                    txtQuantity.setText(Quantity);
                    comboSupplier_id.setSelectedItem(Supplier_ID);
                    txtminimumstock.setText(Minimum_stock_level);
                            }
                else {
                    JOptionPane.showMessageDialog(this, "This is the first record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                
}
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
                  }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        else {
            this.dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_form().setVisible(true);
            }
        });
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
         String s1 = txt_ID.getText();
         
         //check if ID is entered
         if ( s1.isEmpty()){
             JOptionPane.showMessageDialog(this, "Please enter the reord ID to search", "Error", JOptionPane.ERROR_MESSAGE);
             txt_ID.requestFocus();
             return;
         }
         
         /*check if positive integer is entered*/
        if (!s1.matches("\\d+")) {
            JOptionPane.showMessageDialog(this,"ID must be a positive whole number","Invalid ID Format",JOptionPane.ERROR_MESSAGE);
            txt_ID.requestFocus();
            txt_ID.selectAll();
            return;
    }
            
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM inventory WHERE ID = ?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1,s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Item_Name = rs.getString("Item_Name");
                    String Category = rs.getString("Category");
                    String Quantity = rs.getString("Quantity");
                    String Unit = rs.getString("Unit");
                    String Last_restock_date = rs.getString("Last_restock_date");
                    String Supplier_ID = rs.getString("Supplier_ID");
                    String Minimum_stock_level = rs.getString("Minimum_stock_level");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Last_restock_date);
                    comboCategory.setSelectedItem(Category);
                    txtUnit.setText(Unit);
                    txtItem.setText(Item_Name);
                    txtQuantity.setText(Quantity);
                    comboSupplier_id.setSelectedItem(Supplier_ID);
                    txtminimumstock.setText(Minimum_stock_level);
                    JOptionPane.showMessageDialog(null,"Record Retrieved Successfully");
                }
                //no record found
                else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Not Found", JOptionPane.WARNING_MESSAGE);
                    clearFields();
                    txt_ID.requestFocus();
                }
                
}
             catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
         try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM inventory ORDER By ID ASC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Item_Name = rs.getString("Item_Name");
                    String Category = rs.getString("Category");
                    String Quantity = rs.getString("Quantity");
                    String Unit = rs.getString("Unit");
                    String Last_restock_date = rs.getString("Last_restock_date");
                    String Supplier_ID = rs.getString("Supplier_ID");
                    String Minimum_stock_level = rs.getString("Minimum_stock_level");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Last_restock_date);
                    comboCategory.setSelectedItem(Category);
                    txtUnit.setText(Unit);
                    txtItem.setText(Item_Name);
                    txtQuantity.setText(Quantity);
                    comboSupplier_id.setSelectedItem(Supplier_ID);
                    txtminimumstock.setText(Minimum_stock_level);
                    JOptionPane.showMessageDialog(null,"First Record Retrieved Successfully");
                     }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }

                }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM inventory ORDER By ID DESC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Item_Name = rs.getString("Item_Name");
                    String Category = rs.getString("Category");
                    String Quantity = rs.getString("Quantity");
                    String Unit = rs.getString("Unit");
                    String Last_restock_date = rs.getString("Last_restock_date");
                    String Supplier_ID = rs.getString("Supplier_ID");
                    String Minimum_stock_level = rs.getString("Minimum_stock_level");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Last_restock_date);
                    comboCategory.setSelectedItem(Category);
                    txtUnit.setText(Unit);
                    txtItem.setText(Item_Name);
                    txtQuantity.setText(Quantity);
                    comboSupplier_id.setSelectedItem(Supplier_ID);
                    txtminimumstock.setText(Minimum_stock_level);
                    JOptionPane.showMessageDialog(null,"Last Record Retrieved Successfully");
                     }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }

                }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a Branch or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM inventory WHERE ID > ? ORDER By ID ASC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Item_Name = rs.getString("Item_Name");
                    String Category = rs.getString("Category");
                    String Quantity = rs.getString("Quantity");
                    String Unit = rs.getString("Unit");
                    String Last_restock_date = rs.getString("Last_restock_date");
                    String Supplier_ID = rs.getString("Supplier_ID");
                    String Minimum_stock_level = rs.getString("Minimum_stock_level");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Last_restock_date);
                    comboCategory.setSelectedItem(Category);
                    txtUnit.setText(Unit);
                    txtItem.setText(Item_Name);
                    txtQuantity.setText(Quantity);
                    comboSupplier_id.setSelectedItem(Supplier_ID);
                    txtminimumstock.setText(Minimum_stock_level);
                            }
                else {
                    JOptionPane.showMessageDialog(this, "This is the last record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                
}
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
                  }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String s1 = txt_ID.getText();
	if (s1.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please first find the record in the branches to delete", "Error", JOptionPane.ERROR_MESSAGE);
        txt_ID.requestFocus();
        return;
    }
        
			
	try {
            Class.forName("com.mysql.cj.jdbc.Driver"); // register the driver,
            con = DriverManager.getConnection(cs, user, password);
            String deletequery = "DELETE FROM inventory WHERE ID = ?";
            PreparedStatement deleteStmt = con.prepareStatement(deletequery);
            deleteStmt.setString(1, s1);
            int confirm = JOptionPane.showConfirmDialog(this, "Are you Sure You want to Delete record with ID: " + s1 + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm != JOptionPane.YES_OPTION){
                return; //user cancelled
            }
            else{
                int rowsAffected = deleteStmt.executeUpdate();
             if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Record deleted successfully!");
                    // Clear fields after successful deletion
                    clearFields();
                }
            
            else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Error", JOptionPane.ERROR_MESSAGE);
            } 
        }
        }
        catch (SQLException ex) 
        {
            ex.printStackTrace();
	} 
        catch (ClassNotFoundException e) 
        {
            e.printStackTrace();
	} 
        finally {

            try {
		if (st != null) 
                {
                    st.close();
		}
		if (con != null) 
                {
                    con.close();
		}

            } 
            catch (SQLException ex) 
            {
                ex.printStackTrace();
            }
	}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            String s1 = txt_ID.getText();   
            String s2 = txtItem.getText();
            String s3 = (String) comboCategory.getSelectedItem();
            String s4 = txtQuantity.getText();
            String s5 = txtUnit.getText();
            String s6 = txtDate.getText();
            String s7 = (String) comboSupplier_id.getSelectedItem();
            String s8 = txtminimumstock.getText();
            
            /*checking if there is data entered in the ID field*/
            if (!s1.isEmpty()) {
                JOptionPane.showMessageDialog(this,"This field must be empty as it is auto-generated. Please clear this field.","Invalid ID Input",JOptionPane.ERROR_MESSAGE);
                txt_ID.requestFocus(); 
                txt_ID.selectAll();
                return;
            }
            
            /*checking for empty fields*/
            if(s3.equals("--Select category--") || s2.isEmpty() || s7.equals("--Select supplier ID--") || s4.isEmpty() || s5.isEmpty() || s6.equals("YYYY-MM-DD") || s8.isEmpty()){
                JOptionPane.showMessageDialog(this,"Please fill all required fields","Validation Error",JOptionPane.ERROR_MESSAGE);
                if(s3.equals("--Select category--")){
                    comboCategory.requestFocus();
                }
                else if(s7.equals("--Select supplier ID--")){
                    comboCategory.requestFocus();
                }
               
                else if(s4.isEmpty()){
                    txtQuantity.requestFocus();
                }
                else if(s5.isEmpty()){
                    txtUnit.requestFocus();
                }
                else if(s6.equals("YYYY-MM-DD")){
                    txtDate.requestFocus();
                }
                else if(s8.isEmpty()){
                    txtminimumstock.requestFocus();
                }
                else{
                    txtItem.requestFocus();
                }
                return;
            }
            
            /*check number is positive*/
            if (!s4.matches("\\d+")){
                JOptionPane.showMessageDialog(this,"Quantity must be a positive number", "Invalid Data Type",JOptionPane.ERROR_MESSAGE);
                txtQuantity.requestFocus();
                txtQuantity.selectAll();
                return;
            }
            if (!s8.matches("\\d+")){
                JOptionPane.showMessageDialog(this,"minimum stock level must be a positive", "Invalid Data Type",JOptionPane.ERROR_MESSAGE);
                txtminimumstock.requestFocus();
                txtminimumstock.selectAll();
                return;
            }
            if (s5.length() > 15) {
                JOptionPane.showMessageDialog(this, "Unit cannot exceed 15 characters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                txtUnit.requestFocus();
                txtUnit.selectAll();
                return;
            }
            if (s2.length() > 50) {
                JOptionPane.showMessageDialog(this, "Item name cannot exceed 50 characters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                txtItem.requestFocus();
                txtItem.selectAll();
                return;
            }
            if(!s2.matches("^[a-zA-Z\\s\\-\\'\\,]+$")){
                JOptionPane.showMessageDialog(this, "Item cannot contain integers","Invalid Location Format", 
                JOptionPane.ERROR_MESSAGE);
                txtItem.requestFocus();
                txtItem.selectAll();
                return;
            }
            if (txtDate.getText().isEmpty()) {
                txtDate.setText("YYYY-MM-DD");
                txtDate.setForeground(Color.GRAY);
            }
            if (!isValidDate(s6)) {
                JOptionPane.showMessageDialog(this,"Date must be in YYYY-MM-DD format\nExample: 2025-09-17","Invalid Date Format",JOptionPane.ERROR_MESSAGE);
                txtDate.requestFocus();
                txtDate.selectAll();
                return;
    }
            Connection con = null;
            PreparedStatement pstmt = null;
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
               query = "INSERT INTO inventory (Item_Name, Category, Quantity, Unit, Last_restock_date, Supplier_ID, Minimum_stock_level) VALUES (?, ?, ?, ?,?,?,?)";
                pstmt = con.prepareStatement(query);
                
                
                pstmt.setString(1, s2);
                pstmt.setString(2, s3);
                pstmt.setString(3, s4);
                pstmt.setString(4, s5);
                pstmt.setString(5, s6);
                pstmt.setString(6,s7);
                pstmt.setString(7,s8);
                
                /*validate saving*/
                int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to Save this record","Confirm Save",JOptionPane.YES_NO_OPTION);
        
                if (confirm != JOptionPane.YES_OPTION) {
                    return; // User cancelled1
                }
                
                int rowsaffected = pstmt.executeUpdate();
                if(rowsaffected > 0){
                    JOptionPane.showMessageDialog(null,"Record Saved Successfully");
                    clearFields();

                    txtItem.requestFocus();
                }
                else {
                    JOptionPane.showMessageDialog(this, "Failed to save record","Error",JOptionPane.ERROR_MESSAGE);
                }
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboCategory;
    private javax.swing.JComboBox<String> comboSupplier_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtUnit;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txtminimumstock;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        txt_ID.setText("");
        txtDate.setText("YYYY-MM-DD");
        txtDate.setForeground(Color.GRAY);
        comboCategory.setSelectedItem("--Select category--");
        txtUnit.setText("");
        txtItem.setText("");
        txtQuantity.setText("");
        comboSupplier_id.setSelectedItem("--Select supplier ID--");
        txtminimumstock.setText("");
    }
    private boolean isValidDate(String dateStr) {
        if (dateStr == null || !dateStr.matches("\\d{4}-\\d{2}-\\d{2}")) {
            return false;
        }

        try {
            java.sql.Date.valueOf(dateStr);
            return true;
        } catch (IllegalArgumentException e) {
            return false;
        }
}

    private void populatesupplierid() {
         Connection localCon = null;
        Statement localSt = null;
        ResultSet localRs = null;
         
        try {
           Class.forName("com.mysql.cj.jdbc.Driver");
            localCon = DriverManager.getConnection(cs, user, password);
            localSt = localCon.createStatement();
            query = "SELECT ID FROM supplier";
        localRs = localSt.executeQuery(query);
        
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("--Select supplier ID--");
            while (localRs.next()) {
                model.addElement(localRs.getString("ID"));
            }
            comboSupplier_id.setModel(model);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error loading : " + ex.getMessage(), 
                "Database Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } finally {
            try {
                if (localRs != null) localRs.close();
                if (localSt != null) localSt.close();
                if (localCon != null) localCon.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }
}
