/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poultry_farm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HOOKE GEN
 */
public class Mortality_record_form extends javax.swing.JFrame {

    Connection con;
    Statement st;
    String cs;
    
    String user;
    String password;
    
    String query;
    ResultSet rs;
    private String callerRole;
    
    public Mortality_record_form(String callerRole) {
        this.callerRole = callerRole;
        setTitle("MORTALITY RECORD FORM");
        initComponents();
        con = null;
        st = null;
        cs = "jdbc:mysql://localhost:3306/poultry_farm";
        user = "root";
        password = "henry";
        populatereportedby();
        comboReported_by.requestFocus();
    }

    private Mortality_record_form() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        comboPoultry_id = new javax.swing.JComboBox<>();
        txtDate = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtCause = new javax.swing.JTextField();
        txtDisposal_method = new javax.swing.JTextField();
        txtNotes = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        comboReported_by = new javax.swing.JComboBox<>();
        btnLast = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 9, -1, -1));

        jLabel2.setText("Poultry ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 43, -1, -1));

        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 77, -1, -1));

        jLabel4.setText("Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 111, -1, -1));

        jLabel5.setText("Cause");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 145, -1, -1));

        jLabel6.setText("Disposal Method");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 179, -1, -1));

        jLabel7.setText("Reported By");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 213, -1, -1));

        jLabel8.setText("Notes");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 247, -1, -1));
        getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 6, 238, -1));

        comboPoultry_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboPoultry_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 40, 238, -1));

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 74, 238, -1));
        getContentPane().add(txtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 108, 238, -1));

        txtCause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCauseActionPerformed(evt);
            }
        });
        getContentPane().add(txtCause, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 142, 238, -1));

        txtDisposal_method.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisposal_methodActionPerformed(evt);
            }
        });
        getContentPane().add(txtDisposal_method, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 176, 238, -1));
        getContentPane().add(txtNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 244, 345, -1));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 284, -1, -1));

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 284, -1, -1));

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 284, -1, -1));

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 284, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 284, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 284, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 284, -1, -1));

        comboReported_by.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboReported_by, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 210, 238, -1));

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        getContentPane().add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 284, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOOKE GEN\\Documents\\NetBeansProjects\\Poultry_Farm\\poultry_pictures\\financial_transact.jpg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtCauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCauseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCauseActionPerformed

    private void txtDisposal_methodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisposal_methodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisposal_methodActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
         String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a Branch or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM mortality_record WHERE ID < ? ORDER By ID DESC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                     String foundID = rs.getString("ID");
                    String Poultry_ID = rs.getString("Poultry_ID");
                    String Date_of_death = rs.getString("Date_of_death");
                    String Count = rs.getString("Count");
                    String Cause = rs.getString("Cause");
                    String Disposal_method = rs.getString("Disposal_method");
                    String Reported_by = rs.getString("Reported_by");
                    String Notes = rs.getString("Notes");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Date_of_death);
                    comboPoultry_id.setSelectedItem(Poultry_ID);
                    txtNumber.setText(Count);
                    txtCause.setText(Cause);
                    txtDisposal_method.setText(Disposal_method);
                    comboReported_by.setSelectedItem(Reported_by);
                    txtNotes.setText(Notes);
                                }
                else {
                    JOptionPane.showMessageDialog(this, "This is the first record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                
}
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
                  }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
         int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        else {
            this.dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            if ("admin".equals(callerRole)) {
                new Admin_form().setVisible(true); // Open Admin_form
            } else if ("vet".equals(callerRole)) {
                new Vet_form().setVisible(true);
}
              else if ("worker".equals(callerRole)) {
                new Worker_form().setVisible(true); 
                
            } else {
                // Fallback in case callerRole is not set (optional)
                JOptionPane.showMessageDialog(null, "Unknown caller role. Returning to Worker form.", "Warning", JOptionPane.WARNING_MESSAGE);
                new Worker_form().setVisible(true);
            }
        }
    });
            }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM mortality_record ORDER By ID ASC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                    String foundID = rs.getString("ID");
                    String Poultry_ID = rs.getString("Poultry_ID");
                    String Date_of_death = rs.getString("Date_of_death");
                    String Count = rs.getString("Count");
                    String Cause = rs.getString("Cause");
                    String Disposal_method = rs.getString("Disposal_method");
                    String Reported_by = rs.getString("Reported_by");
                    String Notes = rs.getString("Notes");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Date_of_death);
                    comboPoultry_id.setSelectedItem(Poultry_ID);
                    txtNumber.setText(Count);
                    txtCause.setText(Cause);
                    txtDisposal_method.setText(Disposal_method);
                    comboReported_by.setSelectedItem(Reported_by);
                    txtNotes.setText(Notes);
                      JOptionPane.showMessageDialog(null,"First Record Retrieved Successfully");
                     }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }

                }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
         String s1 = txt_ID.getText();
         
         //check if ID is entered
         if ( s1.isEmpty()){
             JOptionPane.showMessageDialog(this, "Please enter the reord ID to search", "Error", JOptionPane.ERROR_MESSAGE);
             txt_ID.requestFocus();
             return;
         }
         
         /*check if positive integer is entered*/
        if (!s1.matches("\\d+")) {
            JOptionPane.showMessageDialog(this,"ID must be a positive whole number","Invalid ID Format",JOptionPane.ERROR_MESSAGE);
            txt_ID.requestFocus();
            txt_ID.selectAll();
            return;
    }
            
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM mortality_record WHERE ID = ?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1,s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Poultry_ID = rs.getString("Poultry_ID");
                    String Date_of_death = rs.getString("Date_of_death");
                    String Count = rs.getString("Count");
                    String Cause = rs.getString("Cause");
                    String Disposal_method = rs.getString("Disposal_method");
                    String Reported_by = rs.getString("Reported_by");
                    String Notes = rs.getString("Notes");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Date_of_death);
                    comboPoultry_id.setSelectedItem(Poultry_ID);
                    txtNumber.setText(Count);
                    txtCause.setText(Cause);
                    txtDisposal_method.setText(Disposal_method);
                    comboReported_by.setSelectedItem(Reported_by);
                    txtNotes.setText(Notes);
                    JOptionPane.showMessageDialog(null,"Record Retrieved Successfully");
                }
                //no record found
                else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Not Found", JOptionPane.WARNING_MESSAGE);
                    clearFields();
                    comboPoultry_id.requestFocus();
                }
                
}
             catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM mortality_record ORDER By ID DESC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                    String foundID = rs.getString("ID");
                    String Poultry_ID = rs.getString("Poultry_ID");
                    String Date_of_death = rs.getString("Date_of_death");
                    String Count = rs.getString("Count");
                    String Cause = rs.getString("Cause");
                    String Disposal_method = rs.getString("Disposal_method");
                    String Reported_by = rs.getString("Reported_by");
                    String Notes = rs.getString("Notes");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Date_of_death);
                    comboPoultry_id.setSelectedItem(Poultry_ID);
                    txtNumber.setText(Count);
                    txtCause.setText(Cause);
                    txtDisposal_method.setText(Disposal_method);
                    comboReported_by.setSelectedItem(Reported_by);
                    txtNotes.setText(Notes);
                      JOptionPane.showMessageDialog(null,"Last Record Retrieved Successfully");
                     }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }

                }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
       String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a Branch or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM mortality_record WHERE ID > ? ORDER By ID ASC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                     String foundID = rs.getString("ID");
                    String Poultry_ID = rs.getString("Poultry_ID");
                    String Date_of_death = rs.getString("Date_of_death");
                    String Count = rs.getString("Count");
                    String Cause = rs.getString("Cause");
                    String Disposal_method = rs.getString("Disposal_method");
                    String Reported_by = rs.getString("Reported_by");
                    String Notes = rs.getString("Notes");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Date_of_death);
                    comboPoultry_id.setSelectedItem(Poultry_ID);
                    txtNumber.setText(Count);
                    txtCause.setText(Cause);
                    txtDisposal_method.setText(Disposal_method);
                    comboReported_by.setSelectedItem(Reported_by);
                    txtNotes.setText(Notes);
                                }
                else {
                    JOptionPane.showMessageDialog(this, "This is the last record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                
}
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
                  }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         String s1 = txt_ID.getText();
	if (s1.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please first find the record in the branches to delete", "Error", JOptionPane.ERROR_MESSAGE);
        txt_ID.requestFocus();
        return;
    }
        
			
	try {
            Class.forName("com.mysql.cj.jdbc.Driver"); // register the driver,
            con = DriverManager.getConnection(cs, user, password);
            String deletequery = "DELETE FROM mortality_record WHERE ID = ?";
            PreparedStatement deleteStmt = con.prepareStatement(deletequery);
            deleteStmt.setString(1, s1);
            int confirm = JOptionPane.showConfirmDialog(this, "Are you Sure You want to Delete Record with ID: " + s1 + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm != JOptionPane.YES_OPTION){
                return; //user cancelled
            }
            else{
                int rowsAffected = deleteStmt.executeUpdate();
             if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Record deleted successfully!");
                    // Clear fields after successful deletion
                    clearFields();
                }
            
            else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Error", JOptionPane.ERROR_MESSAGE);
            } 
        }
        }
        catch (SQLException ex) 
        {
            ex.printStackTrace();
	} 
        catch (ClassNotFoundException e) 
        {
            e.printStackTrace();
	} 
        finally {

            try {
		if (st != null) 
                {
                    st.close();
		}
		if (con != null) 
                {
                    con.close();
		}

            } 
            catch (SQLException ex) 
            {
                ex.printStackTrace();
            }
	}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            String s1 = txt_ID.getText();   
            String s2 = txtDate.getText();
            String s3 = (String) comboPoultry_id.getSelectedItem();
            String s4 = (String) comboReported_by.getSelectedItem();
            String s5 = txtNumber.getText();
            String s6 = txtCause.getText();
            String s7 = txtDisposal_method.getText();
            String s8 = txtNotes.getText();
            
            /*checking if there is data entered in the ID field*/
            if (!s1.isEmpty() || !s2.isEmpty()) {
                JOptionPane.showMessageDialog(this,"This field must be empty as it is auto-generated. Please clear this field.","Invalid ID Input",JOptionPane.ERROR_MESSAGE);
                if(!s1.isEmpty()){
                txt_ID.requestFocus(); 
                txt_ID.selectAll();
                }
                else{
                    txtDate.requestFocus(); 
                    txtDate.selectAll();
                }
                return;
            }
            
            /*checking for empty fields*/
            if(s3.equals("--Select poultry ID--") || s5.isEmpty() || s4.equals("--Reported by--") || s6.isEmpty() || s7.isEmpty() || s8.isEmpty()){
                JOptionPane.showMessageDialog(this,"Please fill all required fields","Validation Error",JOptionPane.ERROR_MESSAGE);
                if(s3.equals("--Select poultry ID--")){
                    comboPoultry_id.requestFocus();
                }
                else if(s4.equals("--Reported by--")){
                    comboReported_by.requestFocus();
                }
               
                else if(s5.isEmpty()){
                    txtNumber.requestFocus();
                }
                else if(s6.isEmpty()){
                    txtCause.requestFocus();
                }
                else if(s7.isEmpty()){
                    txtDisposal_method.requestFocus();
                }
                else{
                    txtNotes.requestFocus();
                }
                return;
            }
            
            /*check number is positive*/
            if (!s5.matches("\\d+")){
                JOptionPane.showMessageDialog(this,"Number must be a positive", "Invalid Data Type",JOptionPane.ERROR_MESSAGE);
                txtNumber.requestFocus();
                txtNumber.selectAll();
                return;
            }
            if (s6.length() > 50) {
                JOptionPane.showMessageDialog(this, "Cause cannot exceed 50 characters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                txtCause.requestFocus();
                txtCause.selectAll();
                return;
            }
            if (s8.length() > 100) {
                JOptionPane.showMessageDialog(this, "Notes cannot exceed 100 characters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                txtNotes.requestFocus();
                txtNotes.selectAll();
                return;
            }
            if (s7.length() > 50) {
                JOptionPane.showMessageDialog(this, "Disposal method cannot exceed 50 characters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                txtDisposal_method.requestFocus();
                txtDisposal_method.selectAll();
                return;
            }
            if(!s6.matches("^[a-zA-Z\\s\\-\\'\\,]+$")){
                JOptionPane.showMessageDialog(this, "Cause cannot contain integers","Invalid Location Format", 
                JOptionPane.ERROR_MESSAGE);
                txtCause.requestFocus();
                txtCause.selectAll();
                return;
            }
            if(!s7.matches("^[a-zA-Z\\s\\-\\'\\,]+$")){
                JOptionPane.showMessageDialog(this, "Disposal method cannot contain integers","Invalid Location Format", 
                JOptionPane.ERROR_MESSAGE);
                txtDisposal_method.requestFocus();
                txtDisposal_method.selectAll();
                return;
            }
                
            
            Connection con = null;
            PreparedStatement pstmt = null;
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
               query = "INSERT INTO mortality_record (Poultry_ID, Count,  Cause, Disposal_method, Reported_by, Notes) VALUES (?, ?, ?, ?,?,?)";
                pstmt = con.prepareStatement(query);
                
                
                pstmt.setString(1, s3);
                pstmt.setString(2, s5);
                pstmt.setString(3, s6);
                pstmt.setString(4, s7);
                pstmt.setString(5,s4);
                pstmt.setString(6,s8);
                
                /*validate saving*/
                int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to Save this record","Confirm Save",JOptionPane.YES_NO_OPTION);
        
                if (confirm != JOptionPane.YES_OPTION) {
                    return; // User cancelled1
                }
                
                int rowsaffected = pstmt.executeUpdate();
                if(rowsaffected > 0){
                    JOptionPane.showMessageDialog(null,"Record Saved Successfully");
                    clearFields();

                    comboPoultry_id.requestFocus();
                }
                else {
                    JOptionPane.showMessageDialog(this, "Failed to save record","Error",JOptionPane.ERROR_MESSAGE);
                }
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mortality_record_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mortality_record_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mortality_record_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mortality_record_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mortality_record_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboPoultry_id;
    private javax.swing.JComboBox<String> comboReported_by;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCause;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDisposal_method;
    private javax.swing.JTextField txtNotes;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txt_ID;
    // End of variables declaration//GEN-END:variables

    private void populatereportedby() {
        Connection localCon = null;
    Statement localSt = null;
    ResultSet localRs = null;
     
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        localCon = DriverManager.getConnection(cs, user, password);
        localSt = localCon.createStatement();
        
        // Populate Poultry ID combo box
        query = "SELECT ID FROM poultry";
        localRs = localSt.executeQuery(query);
        
        DefaultComboBoxModel<String> poultryModel = new DefaultComboBoxModel<>();
        poultryModel.addElement("--Select poultry ID--");
        while (localRs.next()) {
            poultryModel.addElement(localRs.getString("ID"));
        }
        comboPoultry_id.setModel(poultryModel);
        
        // Close the first result set
        localRs.close();
        
        // Populate Reported By combo box with User IDs
        query = "SELECT User_ID FROM users";
        localRs = localSt.executeQuery(query);
        
        DefaultComboBoxModel<String> userModel = new DefaultComboBoxModel<>();
        userModel.addElement("--Reported by--");
        while (localRs.next()) {
            userModel.addElement(localRs.getString("User_ID"));
        }
        comboReported_by.setModel(userModel);
        
    } catch (SQLException | ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(this, "Error loading data: " + ex.getMessage(), 
            "Database Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    } finally {
        try {
            if (localRs != null) localRs.close();
            if (localSt != null) localSt.close();
            if (localCon != null) localCon.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    }

    private void clearFields() {
        txt_ID.setText("");
        txtDate.setText("");
        comboPoultry_id.setSelectedItem("--Select poultry ID--");
        txtNumber.setText("");
        txtCause.setText("");
        txtDisposal_method.setText("");
        comboReported_by.setSelectedItem("--Reported by--");
        txtNotes.setText("");
    }
}
