/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poultry_farm;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HOOKE GEN
 */
public class Poultry_form extends javax.swing.JFrame {

    Connection con;
    Statement st;
    String cs;
    
    String user;
    String password;
    
    String query;
    ResultSet rs;
    
    public Poultry_form() {
        setTitle("POULTRY FORM");
        initComponents();
        con = null;
        st = null;
        cs = "jdbc:mysql://localhost:3306/poultry_farm";
        user = "root";
        password = "henry";
        txtBreed.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        txtBreed = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtHealth_status = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 9, -1, -1));

        jLabel2.setText("Breed");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 49, -1, -1));

        jLabel3.setText("Age");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 89, -1, -1));

        jLabel4.setText("Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 129, -1, -1));

        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 169, -1, -1));

        jLabel6.setText("Health Status");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 209, -1, -1));

        txt_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 6, 253, -1));

        txtBreed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBreedActionPerformed(evt);
            }
        });
        getContentPane().add(txtBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 46, 253, -1));
        getContentPane().add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 86, 253, -1));
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 126, 253, -1));

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 166, 253, -1));
        getContentPane().add(txtHealth_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 206, 253, -1));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 246, -1, -1));

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 246, -1, -1));

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 246, -1, -1));

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 246, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 246, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 246, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 246, -1, -1));

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        getContentPane().add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 246, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOOKE GEN\\Documents\\NetBeansProjects\\Poultry_Farm\\poultry_pictures\\farm.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDActionPerformed

    private void txtBreedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBreedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBreedActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
         String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a Branch or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM poultry WHERE ID < ? ORDER By ID DESC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                     String foundID = rs.getString("ID");
                    String Breed = rs.getString("Breed");
                    String Age = rs.getString("Age");
                    String Entry_Date = rs.getString("Entry_Date");
                    String Quantity = rs.getString("Quantity");
                    String Health_Status = rs.getString("Health_Status");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Entry_Date);
                    txtBreed.setText(Breed);
                    txtAge.setText(Age);
                    txtQuantity.setText(Quantity);
                    txtHealth_status.setText(Health_Status);
                                    }
                else {
                    JOptionPane.showMessageDialog(this, "This is the first record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                
}
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
                  }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        else {
            this.dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_form().setVisible(true);
            }
        });
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
         String s1 = txt_ID.getText();
         
         //check if ID is entered
         if ( s1.isEmpty()){
             JOptionPane.showMessageDialog(this, "Please enter the reord ID to search", "Error", JOptionPane.ERROR_MESSAGE);
             txt_ID.requestFocus();
             return;
         }
         
         /*check if positive integer is entered*/
        if (!s1.matches("\\d+")) {
            JOptionPane.showMessageDialog(this,"ID must be a positive whole number","Invalid ID Format",JOptionPane.ERROR_MESSAGE);
            txt_ID.requestFocus();
            txt_ID.selectAll();
            return;
    }
            
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM poultry WHERE ID = ?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1,s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Breed = rs.getString("Breed");
                    String Age = rs.getString("Age");
                    String Entry_Date = rs.getString("Entry_Date");
                    String Quantity = rs.getString("Quantity");
                    String Health_Status = rs.getString("Health_Status");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Entry_Date);
                    txtBreed.setText(Breed);
                    txtAge.setText(Age);
                    txtQuantity.setText(Quantity);
                    txtHealth_status.setText(Health_Status);
                    JOptionPane.showMessageDialog(null,"Record Retrieved Successfully");
                }
                //no record found
                else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Not Found", JOptionPane.WARNING_MESSAGE);
                    clearFields();
                    txtBreed.requestFocus();
                }
                
}
             catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
         try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM poultry ORDER By ID ASC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                    String foundID = rs.getString("ID");
                    String Breed = rs.getString("Breed");
                    String Age = rs.getString("Age");
                    String Entry_Date = rs.getString("Entry_Date");
                    String Quantity = rs.getString("Quantity");
                    String Health_Status = rs.getString("Health_Status");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Entry_Date);
                    txtBreed.setText(Breed);
                    txtAge.setText(Age);
                    txtQuantity.setText(Quantity);
                    txtHealth_status.setText(Health_Status);
                       JOptionPane.showMessageDialog(null,"First Record Retrieved Successfully");
                     }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }

                }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
         try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM poultry ORDER By ID DESC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                    String foundID = rs.getString("ID");
                    String Breed = rs.getString("Breed");
                    String Age = rs.getString("Age");
                    String Entry_Date = rs.getString("Entry_Date");
                    String Quantity = rs.getString("Quantity");
                    String Health_Status = rs.getString("Health_Status");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Entry_Date);
                    txtBreed.setText(Breed);
                    txtAge.setText(Age);
                    txtQuantity.setText(Quantity);
                    txtHealth_status.setText(Health_Status);
                       JOptionPane.showMessageDialog(null,"Last Record Retrieved Successfully");
                     }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }

                }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a Branch or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM poultry WHERE ID > ? ORDER By ID ASC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                     String foundID = rs.getString("ID");
                    String Breed = rs.getString("Breed");
                    String Age = rs.getString("Age");
                    String Entry_Date = rs.getString("Entry_Date");
                    String Quantity = rs.getString("Quantity");
                    String Health_Status = rs.getString("Health_Status");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Entry_Date);
                    txtBreed.setText(Breed);
                    txtAge.setText(Age);
                    txtQuantity.setText(Quantity);
                    txtHealth_status.setText(Health_Status);
                                    }
                else {
                    JOptionPane.showMessageDialog(this, "This is the last record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                
}
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
                  }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String s1 = txt_ID.getText();
	if (s1.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please first find the record in the branches to delete", "Error", JOptionPane.ERROR_MESSAGE);
        txt_ID.requestFocus();
        return;
    }
        
			
	try {
            Class.forName("com.mysql.cj.jdbc.Driver"); // register the driver,
            con = DriverManager.getConnection(cs, user, password);
            String deletequery = "DELETE FROM poultry WHERE ID = ?";
            PreparedStatement deleteStmt = con.prepareStatement(deletequery);
            deleteStmt.setString(1, s1);
            int confirm = JOptionPane.showConfirmDialog(this, "Are you Sure You want to Delete Record with ID: " + s1 + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm != JOptionPane.YES_OPTION){
                return; //user cancelled
            }
            else{
                int rowsAffected = deleteStmt.executeUpdate();
             if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Record deleted successfully!");
                    // Clear fields after successful deletion
                    clearFields();
                }
            
            else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Error", JOptionPane.ERROR_MESSAGE);
            } 
        }
        }
        catch (SQLException ex) 
        {
            ex.printStackTrace();
	} 
        catch (ClassNotFoundException e) 
        {
            e.printStackTrace();
	} 
        finally {

            try {
		if (st != null) 
                {
                    st.close();
		}
		if (con != null) 
                {
                    con.close();
		}

            } 
            catch (SQLException ex) 
            {
                ex.printStackTrace();
            }
	}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            String s1 = txt_ID.getText();   
            String s2 = txtBreed.getText();
            String s3 = txtAge.getText();
            String s4 = txtDate.getText();
            String s5 = txtQuantity.getText();
            String s6 = txtHealth_status.getText();
           
            
            /*checking if there is data entered in the ID field*/
            if (!s1.isEmpty() || !s4.isEmpty()) {
                JOptionPane.showMessageDialog(this,"This field must be empty as it is auto-generated. Please clear this field.","Invalid ID Input",JOptionPane.ERROR_MESSAGE);
                if(!s1.isEmpty()){
                txt_ID.requestFocus(); 
                txt_ID.selectAll();
                }
                else{
                    txtDate.requestFocus(); 
                    txtDate.selectAll();
                }
                return;
            }
            
            /*checking for empty fields*/
            if(s3.isEmpty() || s2.isEmpty() || s5.isEmpty() || s6.isEmpty()){
                JOptionPane.showMessageDialog(this,"Please fill all required fields","Validation Error",JOptionPane.ERROR_MESSAGE);
                if(s3.isEmpty()){
                    txtAge.requestFocus();
                }
                
                else if(s2.isEmpty()){
                    txtBreed.requestFocus();
                }
                else if(s5.isEmpty()){
                    txtQuantity.requestFocus();
                }
                else{
                    txtHealth_status.requestFocus();
                }
                return;
            }
            
            /*check number is positive*/
            if (!s5.matches("\\d+")){
                JOptionPane.showMessageDialog(this,"Quantity must be a positive number", "Invalid Data Type",JOptionPane.ERROR_MESSAGE);
                txtQuantity.requestFocus();
                txtQuantity.selectAll();
                return;
            }
            if (!s3.matches("\\d+")){
                JOptionPane.showMessageDialog(this,"Age must be a positive", "Invalid Data Type",JOptionPane.ERROR_MESSAGE);
                txtAge.requestFocus();
                txtAge.selectAll();
                return;
            }
            if (s2.length() > 15) {
                JOptionPane.showMessageDialog(this, "Breed cannot exceed 15 characters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                txtBreed.requestFocus();
                txtBreed.selectAll();
                return;
            }
            if (s6.length() > 50) {
                JOptionPane.showMessageDialog(this, "Health status cannot exceed 50 characters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                txtHealth_status.requestFocus();
                txtHealth_status.selectAll();
                return;
            }
            
            if(!s2.matches("^[a-zA-Z\\s\\-\\'\\,]+$")){
                JOptionPane.showMessageDialog(this, "Breed cannot contain integers","Invalid Location Format", 
                JOptionPane.ERROR_MESSAGE);
                txtBreed.requestFocus();
                txtBreed.selectAll();
                return;
            }
            if(!s6.matches("^[a-zA-Z\\s\\-\\'\\,]+$")){
                JOptionPane.showMessageDialog(this, "Health status cannot contain integers","Invalid Location Format", 
                JOptionPane.ERROR_MESSAGE);
                txtHealth_status.requestFocus();
                txtHealth_status.selectAll();
                return;
            }
    
            Connection con = null;
            PreparedStatement pstmt = null;
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
               query = "INSERT INTO poultry (Breed, Age, Quantity, Health_Status) VALUES (?, ?, ?, ?)";
                pstmt = con.prepareStatement(query);
                
                
                pstmt.setString(1, s2);
                pstmt.setString(2, s3);
                pstmt.setString(3, s5);
                pstmt.setString(4, s6);
                
                /*validate saving*/
                int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to Save this record","Confirm Save",JOptionPane.YES_NO_OPTION);
        
                if (confirm != JOptionPane.YES_OPTION) {
                    return; // User cancelled1
                }
                
                int rowsaffected = pstmt.executeUpdate();
                if(rowsaffected > 0){
                    JOptionPane.showMessageDialog(null,"Record Saved Successfully");
                    clearFields();

                    txtBreed.requestFocus();
                }
                else {
                    JOptionPane.showMessageDialog(this, "Failed to save record","Error",JOptionPane.ERROR_MESSAGE);
                }
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Poultry_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Poultry_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Poultry_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Poultry_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Poultry_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBreed;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtHealth_status;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txt_ID;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        txt_ID.setText("");
        txtDate.setText("");
        txtBreed.setText("");
        txtAge.setText("");
        txtQuantity.setText("");
        txtHealth_status.setText("");
    }
}
