/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poultry_farm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HOOKE GEN
 */
public class Task_Assignment_form extends javax.swing.JFrame {

    Statement st;
    String cs;
    
    String user;
    String password;
    
    String query;
    ResultSet rs;
    Connection con;
    
    public Task_Assignment_form() {
        setTitle("TASK ASSIGNMENT");
        initComponents();
        con = null;
        st = null;
        cs = "jdbc:mysql://localhost:3306/poultry_farm";
        user = "root";
        password = "henry";
        txtDescription.requestFocus();
        populatereportedby();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        comboAssigned_to = new javax.swing.JComboBox<>();
        comboAssigned_by = new javax.swing.JComboBox<>();
        txtDate = new javax.swing.JTextField();
        txtDate_due = new javax.swing.JTextField();
        comboStatus = new javax.swing.JComboBox<>();
        comboPriority = new javax.swing.JComboBox<>();
        txtDate_completion = new javax.swing.JTextField();
        txtNotes = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        txtPrevious = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 9, -1, -1));

        jLabel2.setText("Task Description");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 43, -1, -1));

        jLabel3.setText("Assigned To");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 77, -1, -1));

        jLabel4.setText("Assigned By");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 111, -1, -1));

        jLabel5.setText("Assigned Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 145, -1, -1));

        jLabel6.setText("Due Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 179, -1, -1));

        jLabel7.setText("Status");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 213, -1, -1));

        jLabel8.setText("Priority");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 247, -1, -1));

        jLabel9.setText("Completion Date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 281, -1, -1));

        jLabel10.setText("Notes");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 315, -1, -1));
        getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 6, 270, -1));
        getContentPane().add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 40, 270, -1));

        comboAssigned_to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboAssigned_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 74, 270, -1));

        comboAssigned_by.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboAssigned_by, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 108, 270, -1));
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 142, 270, -1));
        getContentPane().add(txtDate_due, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 176, 270, -1));

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Status--", "PENDING", "IN_PROGRESS", "COMPLETED", "CANCELLED" }));
        getContentPane().add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 210, 270, -1));

        comboPriority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Priority--", "LOW", "MEDIUM", "HIGH", "URGENT" }));
        getContentPane().add(comboPriority, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 244, 270, -1));
        getContentPane().add(txtDate_completion, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 278, 270, -1));
        getContentPane().add(txtNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 312, 379, -1));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 352, -1, -1));

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 352, -1, -1));

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 352, -1, -1));

        txtPrevious.setText("Previous");
        txtPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 352, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 352, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 352, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 352, -1, -1));

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        getContentPane().add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 352, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOOKE GEN\\Documents\\NetBeansProjects\\Poultry_Farm\\poultry_pictures\\financial_transact.jpg")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreviousActionPerformed
          String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a Branch or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM task_assignment WHERE ID < ? ORDER By ID DESC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                     String foundID = rs.getString("ID");
                    String Task_description = rs.getString("Task_description");
                    String Assigned_to = rs.getString("Assigned_to");
                    String Assigned_by = rs.getString("Assigned_by");
                    String Assigned_date = rs.getString("Assigned_date");
                    String Due_date = rs.getString("Due_date");
                    String Status = rs.getString("Status");
                    String Priority = rs.getString("Priority");
                    String Completion_Date = rs.getString("Completion_Date");
                    String Notes = rs.getString("Notes");
                    
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Assigned_date);
                    comboAssigned_to.setSelectedItem(Assigned_to);
                    comboAssigned_by.setSelectedItem(Assigned_by);
                    txtDescription.setText(Task_description);
                    txtDate_due.setText(Due_date);
                    comboStatus.setSelectedItem(Status);
                    txtDate_completion.setText(Completion_Date);
                    comboPriority.setSelectedItem(Priority);
                    txtNotes.setText(Notes);
                                 }
                else {
                    JOptionPane.showMessageDialog(this, "This is the first record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                
}
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
                  }
    }//GEN-LAST:event_txtPreviousActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        else {
            this.dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_form().setVisible(true);
            }
        });
        }
                 
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM task_assignment ORDER By ID ASC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                     //record found
                    String foundID = rs.getString("ID");
                    String Task_description = rs.getString("Task_description");
                    String Assigned_to = rs.getString("Assigned_to");
                    String Assigned_by = rs.getString("Assigned_by");
                    String Assigned_date = rs.getString("Assigned_date");
                    String Due_date = rs.getString("Due_date");
                    String Status = rs.getString("Status");
                    String Priority = rs.getString("Priority");
                    String Completion_Date = rs.getString("Completion_Date");
                    String Notes = rs.getString("Notes");
                    
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Assigned_date);
                    comboAssigned_to.setSelectedItem(Assigned_to);
                    comboAssigned_by.setSelectedItem(Assigned_by);
                    txtDescription.setText(Task_description);
                    txtDate_due.setText(Due_date);
                    comboStatus.setSelectedItem(Status);
                    txtDate_completion.setText(Completion_Date);
                    comboPriority.setSelectedItem(Priority);
                    txtNotes.setText(Notes);
                             JOptionPane.showMessageDialog(null,"First Record Retrieved Successfully");
                     }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }

                }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String s1 = txt_ID.getText();
         
         //check if ID is entered
         if ( s1.isEmpty()){
             JOptionPane.showMessageDialog(this, "Please enter the reord ID to search", "Error", JOptionPane.ERROR_MESSAGE);
             txt_ID.requestFocus();
             return;
         }
         
         /*check if positive integer is entered*/
        if (!s1.matches("\\d+")) {
            JOptionPane.showMessageDialog(this,"ID must be a positive whole number","Invalid ID Format",JOptionPane.ERROR_MESSAGE);
            txt_ID.requestFocus();
            txt_ID.selectAll();
            return;
    }
            
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM task_assignment WHERE ID = ?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1,s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Task_description = rs.getString("Task_description");
                    String Assigned_to = rs.getString("Assigned_to");
                    String Assigned_by = rs.getString("Assigned_by");
                    String Assigned_date = rs.getString("Assigned_date");
                    String Due_date = rs.getString("Due_date");
                    String Status = rs.getString("Status");
                    String Priority = rs.getString("Priority");
                    String Completion_Date = rs.getString("Completion_Date");
                    String Notes = rs.getString("Notes");
                    
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Assigned_date);
                    comboAssigned_to.setSelectedItem(Assigned_to);
                    comboAssigned_by.setSelectedItem(Assigned_by);
                    txtDescription.setText(Task_description);
                    txtDate_due.setText(Due_date);
                    comboStatus.setSelectedItem(Status);
                    txtDate_completion.setText(Completion_Date);
                    comboPriority.setSelectedItem(Priority);
                    txtNotes.setText(Notes);
                    JOptionPane.showMessageDialog(null,"Record Retrieved Successfully");
                }
                //no record found
                else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Not Found", JOptionPane.WARNING_MESSAGE);
                    clearFields();
                    txt_ID.requestFocus();
                }
                
}
             catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM task_assignment ORDER By ID DESC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                     //record found
                    String foundID = rs.getString("ID");
                    String Task_description = rs.getString("Task_description");
                    String Assigned_to = rs.getString("Assigned_to");
                    String Assigned_by = rs.getString("Assigned_by");
                    String Assigned_date = rs.getString("Assigned_date");
                    String Due_date = rs.getString("Due_date");
                    String Status = rs.getString("Status");
                    String Priority = rs.getString("Priority");
                    String Completion_Date = rs.getString("Completion_Date");
                    String Notes = rs.getString("Notes");
                    
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Assigned_date);
                    comboAssigned_to.setSelectedItem(Assigned_to);
                    comboAssigned_by.setSelectedItem(Assigned_by);
                    txtDescription.setText(Task_description);
                    txtDate_due.setText(Due_date);
                    comboStatus.setSelectedItem(Status);
                    txtDate_completion.setText(Completion_Date);
                    comboPriority.setSelectedItem(Priority);
                    txtNotes.setText(Notes);
                             JOptionPane.showMessageDialog(null,"Last Record Retrieved Successfully");
                     }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }

                }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
         String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a Branch or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM task_assignment WHERE ID > ? ORDER By ID ASC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                     String foundID = rs.getString("ID");
                    String Task_description = rs.getString("Task_description");
                    String Assigned_to = rs.getString("Assigned_to");
                    String Assigned_by = rs.getString("Assigned_by");
                    String Assigned_date = rs.getString("Assigned_date");
                    String Due_date = rs.getString("Due_date");
                    String Status = rs.getString("Status");
                    String Priority = rs.getString("Priority");
                    String Completion_Date = rs.getString("Completion_Date");
                    String Notes = rs.getString("Notes");
                    
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Assigned_date);
                    comboAssigned_to.setSelectedItem(Assigned_to);
                    comboAssigned_by.setSelectedItem(Assigned_by);
                    txtDescription.setText(Task_description);
                    txtDate_due.setText(Due_date);
                    comboStatus.setSelectedItem(Status);
                    txtDate_completion.setText(Completion_Date);
                    comboPriority.setSelectedItem(Priority);
                    txtNotes.setText(Notes);
                                 }
                else {
                    JOptionPane.showMessageDialog(this, "This is the last record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                
}
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
                  }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         String s1 = txt_ID.getText();
	if (s1.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please first find the record in the branches to delete", "Error", JOptionPane.ERROR_MESSAGE);
        txt_ID.requestFocus();
        return;
    }
        
			
	try {
            Class.forName("com.mysql.cj.jdbc.Driver"); // register the driver,
            con = DriverManager.getConnection(cs, user, password);
            String deletequery = "DELETE FROM task_assignment WHERE ID = ?";
            PreparedStatement deleteStmt = con.prepareStatement(deletequery);
            deleteStmt.setString(1, s1);
            int confirm = JOptionPane.showConfirmDialog(this, "Are you Sure You want to Delete Record with ID: " + s1 + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm != JOptionPane.YES_OPTION){
                return; //user cancelled
            }
            else{
                int rowsAffected = deleteStmt.executeUpdate();
             if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Record deleted successfully!");
                    // Clear fields after successful deletion
                    clearFields();
                    txtDescription.requestFocus();
                }
            
            else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Error", JOptionPane.ERROR_MESSAGE);
            } 
        }
        }
        catch (SQLException ex) 
        {
            ex.printStackTrace();
	} 
        catch (ClassNotFoundException e) 
        {
            e.printStackTrace();
	} 
        finally {

            try {
		if (st != null) 
                {
                    st.close();
		}
		if (con != null) 
                {
                    con.close();
		}

            } 
            catch (SQLException ex) 
            {
                ex.printStackTrace();
            }
	}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            String s1 = txt_ID.getText();   
            String s2 = txtDate.getText();
            String s3 = (String) comboAssigned_by.getSelectedItem();
            String s4 = (String) comboAssigned_to.getSelectedItem();
            String s5 = txtDescription.getText();
            String s6 = txtDate_due.getText();
            String s7 = (String) comboStatus.getSelectedItem();
            String s8 = txtDate_completion.getText();
            String s9 = (String) comboPriority.getSelectedItem();
            String s10 = txtNotes.getText();
            
            /*checking if there is data entered in the ID field*/
            if (!s1.isEmpty() || !s2.isEmpty()) {
                JOptionPane.showMessageDialog(this,"This field must be empty as it is auto-generated. Please clear this field.","Invalid ID Input",JOptionPane.ERROR_MESSAGE);
                if(!s1.isEmpty()){
                txt_ID.requestFocus(); 
                txt_ID.selectAll();
                }
                else{
                    txtDate.requestFocus(); 
                    txtDate.selectAll();
                }
                return;
            }
            
            /*checking for empty fields*/
            if(s3.equals("--Select Employee ID--") || s5.isEmpty() || s4.equals("--Select Employee ID--") || s6.isEmpty() || s7.equals("--Select Status--") || s8.isEmpty() || s9.equals("--Select Priority--") || s10.isEmpty()){
                JOptionPane.showMessageDialog(this,"Please fill all required fields","Validation Error",JOptionPane.ERROR_MESSAGE);
                if(s3.equals("--Select Employee ID--")){
                    comboAssigned_by.requestFocus();
                }
                else if(s4.equals("--Select Employee ID--")){
                    comboAssigned_to.requestFocus();
                }
               
                else if(s7.equals("--Select Status--")){
                    comboStatus.requestFocus();
                }
                else if(s5.isEmpty()){
                    txtDescription.requestFocus();
                }
                else if(s6.isEmpty()){
                    txtDate_due.requestFocus();
                }
                else if(s8.isEmpty()){
                    txtDate_completion.requestFocus();
                }
                else if(s9.equals("--Select Priority--")){
                    comboPriority.requestFocus();
                }
                else{
                    txtNotes.requestFocus();
                }
                return;
            }
            
            /*check number is positive*/
         
            if (s5.length() > 100) {
                JOptionPane.showMessageDialog(this, "Description cannot exceed 100 characters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                txtDescription.requestFocus();
                txtDescription.selectAll();
                return;
            }
            if (s10.length() > 100) {
                JOptionPane.showMessageDialog(this, "Notes cannot exceed 100 characters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                txtNotes.requestFocus();
                txtNotes.selectAll();
                return;
            }
            
            if (!isValidDate(s6)) {
                JOptionPane.showMessageDialog(this,"Due date must be in YYYY-MM-DD format\nExample: 2025-09-17","Invalid Date Format",JOptionPane.ERROR_MESSAGE);
                txtDate_due.requestFocus();
                txtDate_due.selectAll();
                return;
    }
            if (!isValidDate(s8)) {
                JOptionPane.showMessageDialog(this,"Completion date must be in YYYY-MM-DD format\nExample: 2025-09-17","Invalid Date Format",JOptionPane.ERROR_MESSAGE);
                txtDate_completion.requestFocus();
                txtDate_completion.selectAll();
                return;
    }
    
            Connection con = null;
            PreparedStatement pstmt = null;
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
               query = "INSERT INTO task_assignment (Task_description, Assigned_to, Assigned_by, Due_date, Status, Priority, Completion_Date, Notes) VALUES (?, ?, ?, ?,?,?,?,?)";
                pstmt = con.prepareStatement(query);
                
                
                pstmt.setString(1, s5);
                pstmt.setString(2, s4);
                pstmt.setString(3, s3);
                pstmt.setString(4, s6);
                pstmt.setString(5,s7);
                pstmt.setString(6,s9);
                pstmt.setString(7,s8);
                pstmt.setString(8,s10);
                
                /*validate saving*/
                int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to Save this record","Confirm Save",JOptionPane.YES_NO_OPTION);
        
                if (confirm != JOptionPane.YES_OPTION) {
                    return; // User cancelled1
                }
                
                int rowsaffected = pstmt.executeUpdate();
                if(rowsaffected > 0){
                    JOptionPane.showMessageDialog(null,"Record Saved Successfully");
                    clearFields();

                    txtDescription.requestFocus();
                }
                else {
                    JOptionPane.showMessageDialog(this, "Failed to save record","Error",JOptionPane.ERROR_MESSAGE);
                }
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Task_Assignment_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Task_Assignment_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Task_Assignment_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Task_Assignment_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Task_Assignment_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboAssigned_by;
    private javax.swing.JComboBox<String> comboAssigned_to;
    private javax.swing.JComboBox<String> comboPriority;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDate_completion;
    private javax.swing.JTextField txtDate_due;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtNotes;
    private javax.swing.JButton txtPrevious;
    private javax.swing.JTextField txt_ID;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        txt_ID.setText("");
        txtDate.setText("");
        comboAssigned_to.setSelectedItem("--Select Employee ID--");
        comboAssigned_by.setSelectedItem("--Select Employee ID--");
        txtDescription.setText("");
        txtDate_due.setText("");
        comboStatus.setSelectedItem("--Select Status--");
        txtDate_completion.setText("");
        comboPriority.setSelectedItem("--Select Priority--");
        txtNotes.setText("");
    }
     private boolean isValidDate(String dateStr) {
        if (dateStr == null || !dateStr.matches("\\d{4}-\\d{2}-\\d{2}")) {
            return false;
        }

        try {
            java.sql.Date.valueOf(dateStr);
            return true;
        } catch (IllegalArgumentException e) {
            return false;
        }
}
      private void populatereportedby() {
        Connection localCon = null;
    Statement localSt = null;
    ResultSet localRs = null;
     
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        localCon = DriverManager.getConnection(cs, user, password);
        localSt = localCon.createStatement();
        
        // Populate Poultry ID combo box
        query = "SELECT ID FROM employees";
        localRs = localSt.executeQuery(query);
        
        DefaultComboBoxModel<String> poultryModel = new DefaultComboBoxModel<>();
        poultryModel.addElement("--Select Employee ID--");
        while (localRs.next()) {
            poultryModel.addElement(localRs.getString("ID"));
        }
        comboAssigned_to.setModel(poultryModel);
        
        // Close the first result set
        localRs.close();
        
        // Populate Reported By combo box with User IDs
        query = "SELECT ID FROM employees";
        localRs = localSt.executeQuery(query);
        
        DefaultComboBoxModel<String> userModel = new DefaultComboBoxModel<>();
        userModel.addElement("--Select Employee ID--");
        while (localRs.next()) {
            userModel.addElement(localRs.getString("ID"));
        }
        comboAssigned_by.setModel(userModel);
        
    } catch (SQLException | ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(this, "Error loading data: " + ex.getMessage(), 
            "Database Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    } finally {
        try {
            if (localRs != null) localRs.close();
            if (localSt != null) localSt.close();
            if (localCon != null) localCon.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
      }
     
}
