/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poultry_farm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HOOKE GEN
 */
public class Vaccination_schedule_form extends javax.swing.JFrame {

    Statement st;
    String cs;
    
    String user;
    String password;
    
    String query;
    ResultSet rs;
    Connection con;
    private String callerRole;
    
    public Vaccination_schedule_form(String callerRole) {
        this.callerRole = callerRole;
        setTitle("VACCINATION SCHEDULE");
        initComponents();
         con = null;
        st = null;
        cs = "jdbc:mysql://localhost:3306/poultry_farm";
        user = "root";
        password = "henry";
        comboPoultry_id.requestFocus();
        populatepoultryid();
    }

    private Vaccination_schedule_form() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        comboPoultry_id = new javax.swing.JComboBox<>();
        txtVaccine = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtAdministered_date = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        comboAdministered_by = new javax.swing.JComboBox<>();
        btnLast = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 9, -1, -1));

        jLabel2.setText("Poultry ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 43, -1, -1));

        jLabel3.setText("Vaccine Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 77, -1, -1));

        jLabel4.setText("Scheduled Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 111, -1, -1));

        jLabel5.setText("Administered Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 145, -1, -1));

        jLabel6.setText("Administered By");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 179, -1, -1));
        getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 6, 264, -1));

        comboPoultry_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboPoultry_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 40, 264, -1));
        getContentPane().add(txtVaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 74, 264, -1));

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 108, 264, -1));
        getContentPane().add(txtAdministered_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 142, 264, -1));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 216, -1, -1));

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 216, -1, -1));

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 216, -1, -1));

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 216, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 216, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 216, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 216, -1, -1));

        comboAdministered_by.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboAdministered_by, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 176, 264, -1));

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        getContentPane().add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 216, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOOKE GEN\\Documents\\NetBeansProjects\\Poultry_Farm\\poultry_pictures\\vaccination.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
            String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a record or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM vaccination_schedule WHERE ID < ? ORDER By ID DESC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                        //record found
                    String foundID = rs.getString("ID");
                    String Poultry_ID = rs.getString("Poultry_ID");
                    String Vaccine_name = rs.getString("Vaccine_name");
                    String Scheduled_date = rs.getString("Scheduled_date");
                    String Administered_date = rs.getString("Administered_date");
                    String Administered_by = rs.getString("Administered_by");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Scheduled_date);
                    comboPoultry_id.setSelectedItem(Poultry_ID);
                    txtVaccine.setText(Vaccine_name);
                    txtAdministered_date.setText(Administered_date);
                    comboAdministered_by.setSelectedItem(Administered_by);
                                      }
                else {
                    JOptionPane.showMessageDialog(this, "This is the first record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                
}
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
                  }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
         int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        else {
            this.dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            if ("admin".equals(callerRole)) {
                new Admin_form().setVisible(true); // Open Admin_form
            } else if ("vet".equals(callerRole)) {
                new Vet_form().setVisible(true); // Open Worker_form
            } else {
                // Fallback in case callerRole is not set (optional)
                JOptionPane.showMessageDialog(null, "Unknown caller role. Returning to Worker form.", "Warning", JOptionPane.WARNING_MESSAGE);
                new Worker_form().setVisible(true);
            }
        }
    });
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String s1 = txt_ID.getText();
         
         //check if ID is entered
         if ( s1.isEmpty()){
             JOptionPane.showMessageDialog(this, "Please enter the reord ID to search", "Error", JOptionPane.ERROR_MESSAGE);
             txt_ID.requestFocus();
             return;
         }
         
         /*check if positive integer is entered*/
        if (!s1.matches("\\d+")) {
            JOptionPane.showMessageDialog(this,"ID must be a positive whole number","Invalid ID Format",JOptionPane.ERROR_MESSAGE);
            txt_ID.requestFocus();
            txt_ID.selectAll();
            return;
    }
            
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM vaccination_schedule WHERE ID = ?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1,s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                    //record found
                    String foundID = rs.getString("ID");
                    String Poultry_ID = rs.getString("Poultry_ID");
                    String Vaccine_name = rs.getString("Vaccine_name");
                    String Scheduled_date = rs.getString("Scheduled_date");
                    String Administered_date = rs.getString("Administered_date");
                    String Administered_by = rs.getString("Administered_by");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Scheduled_date);
                    comboPoultry_id.setSelectedItem(Poultry_ID);
                    txtVaccine.setText(Vaccine_name);
                    txtAdministered_date.setText(Administered_date);
                    comboAdministered_by.setSelectedItem(Administered_by);
                    JOptionPane.showMessageDialog(null,"Record Retrieved Successfully");
                }
                //no record found
                else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Not Found", JOptionPane.WARNING_MESSAGE);
                    clearFields();
                    comboPoultry_id.requestFocus();
                }
                
}
             catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}  
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM vaccination_schedule ORDER By ID ASC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                       //record found
                    String foundID = rs.getString("ID");
                    String Poultry_ID = rs.getString("Poultry_ID");
                    String Vaccine_name = rs.getString("Vaccine_name");
                    String Scheduled_date = rs.getString("Scheduled_date");
                    String Administered_date = rs.getString("Administered_date");
                    String Administered_by = rs.getString("Administered_by");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Scheduled_date);
                    comboPoultry_id.setSelectedItem(Poultry_ID);
                    txtVaccine.setText(Vaccine_name);
                    txtAdministered_date.setText(Administered_date);
                    comboAdministered_by.setSelectedItem(Administered_by);
                    JOptionPane.showMessageDialog(null,"First Record Retrieved Successfully");
                     }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }

                }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM vaccination_schedule ORDER By ID DESC LIMIT 1";
                st = con.createStatement();
                
                rs = st.executeQuery(query);
                if (rs.next()){
                       //record found
                    String foundID = rs.getString("ID");
                    String Poultry_ID = rs.getString("Poultry_ID");
                    String Vaccine_name = rs.getString("Vaccine_name");
                    String Scheduled_date = rs.getString("Scheduled_date");
                    String Administered_date = rs.getString("Administered_date");
                    String Administered_by = rs.getString("Administered_by");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Scheduled_date);
                    comboPoultry_id.setSelectedItem(Poultry_ID);
                    txtVaccine.setText(Vaccine_name);
                    txtAdministered_date.setText(Administered_date);
                    comboAdministered_by.setSelectedItem(Administered_by);
                    JOptionPane.showMessageDialog(null,"Last Record Retrieved Successfully");
                     }
                 else {
                    JOptionPane.showMessageDialog(this, "No records found in the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
                
}
         catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }

                }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
          String s1 = txt_ID.getText();
       if (s1.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please find a Branch or use the First button", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
                query = "SELECT * FROM vaccination_schedule WHERE ID > ? ORDER By ID ASC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, s1);
                
                rs = pst.executeQuery();
                if (rs.next()){
                        //record found
                    String foundID = rs.getString("ID");
                    String Poultry_ID = rs.getString("Poultry_ID");
                    String Vaccine_name = rs.getString("Vaccine_name");
                    String Scheduled_date = rs.getString("Scheduled_date");
                    String Administered_date = rs.getString("Administered_date");
                    String Administered_by = rs.getString("Administered_by");
                    
                    //update the text fields
                    txt_ID.setText(foundID);
                    txtDate.setText(Scheduled_date);
                    comboPoultry_id.setSelectedItem(Poultry_ID);
                    txtVaccine.setText(Vaccine_name);
                    txtAdministered_date.setText(Administered_date);
                    comboAdministered_by.setSelectedItem(Administered_by);
                                      }
                else {
                    JOptionPane.showMessageDialog(this, "This is the last record from the database", "Info", JOptionPane.INFORMATION_MESSAGE);
                
}
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
                  }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
          String s1 = txt_ID.getText();
	if (s1.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please first find the record in the branches to delete", "Error", JOptionPane.ERROR_MESSAGE);
        txt_ID.requestFocus();
        return;
    }
        
			
	try {
            Class.forName("com.mysql.cj.jdbc.Driver"); // register the driver,
            con = DriverManager.getConnection(cs, user, password);
            String deletequery = "DELETE FROM vaccination_schedule WHERE ID = ?";
            PreparedStatement deleteStmt = con.prepareStatement(deletequery);
            deleteStmt.setString(1, s1);
            int confirm = JOptionPane.showConfirmDialog(this, "Are you Sure You want to Delete Record with ID: " + s1 + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm != JOptionPane.YES_OPTION){
                return; //user cancelled
            }
            else{
                int rowsAffected = deleteStmt.executeUpdate();
             if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Record deleted successfully!");
                    // Clear fields after successful deletion
                    clearFields();
                    comboPoultry_id.requestFocus();
                }
            
            else {
                    JOptionPane.showMessageDialog(this, "No record found with ID: " + s1, "Error", JOptionPane.ERROR_MESSAGE);
            } 
        }
        }
        catch (SQLException ex) 
        {
            ex.printStackTrace();
	} 
        catch (ClassNotFoundException e) 
        {
            e.printStackTrace();
	} 
        finally {

            try {
		if (st != null) 
                {
                    st.close();
		}
		if (con != null) 
                {
                    con.close();
		}

            } 
            catch (SQLException ex) 
            {
                ex.printStackTrace();
            }
	}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            String s1 = txt_ID.getText();   
            String s2 = txtDate.getText();
            String s3 = (String) comboPoultry_id.getSelectedItem();
            String s4 = txtVaccine.getText();
            String s5 = txtAdministered_date.getText();
            String s6 = (String) comboAdministered_by.getSelectedItem();
            
            /*checking if there is data entered in the ID field*/
            if (!s1.isEmpty() || !s5.isEmpty()) {
                JOptionPane.showMessageDialog(this,"This field must be empty as it is auto-generated. Please clear this field.","Invalid ID Input",JOptionPane.ERROR_MESSAGE);
                if(!s1.isEmpty()){
                txt_ID.requestFocus(); 
                txt_ID.selectAll();
                }
                else{
                    txtAdministered_date.requestFocus(); 
                    txtAdministered_date.selectAll();
                }
                return;
            }
            
            /*checking for empty fields*/
            if(s3.equals("--Select Poultry ID--") || s4.isEmpty() || s2.isEmpty() || s6.equals("--Select Employee ID--")){
                JOptionPane.showMessageDialog(this,"Please fill all required fields","Validation Error",JOptionPane.ERROR_MESSAGE);
                if(s3.equals("--Select Poultry ID--")){
                    comboPoultry_id.requestFocus();
                }
                
                else if(s4.isEmpty()){
                    txtVaccine.requestFocus();
                }
                else if(s2.isEmpty()){
                    txtDate.requestFocus();
                }
                else if(s6.equals("--Select Employee ID--")){
                    comboAdministered_by.requestFocus();
                }
                
                return;
            }
            
            /*check number is positive*/
           
            if (s4.length() > 40) {
                JOptionPane.showMessageDialog(this, "Vaccine cannot exceed 40 characters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                txtVaccine.requestFocus();
                txtVaccine.selectAll();
                return;
            }
            if (!isValidDate(s2)) {
                JOptionPane.showMessageDialog(this,"Scheduled date must be in YYYY-MM-DD format\nExample: 2025-09-17","Invalid Date Format",JOptionPane.ERROR_MESSAGE);
                txtDate.requestFocus();
                txtDate.selectAll();
                return;
    }
            
            Connection con = null;
            PreparedStatement pstmt = null;
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(cs, user, password);
               query = "INSERT INTO Vaccination_schedule (Poultry_ID, Vaccine_name, Scheduled_date, Administered_by) VALUES (?, ?, ?, ?)";
                pstmt = con.prepareStatement(query);
                
                
                pstmt.setString(1, s3);
                pstmt.setString(2, s4);
                pstmt.setString(3, s2);
                pstmt.setString(4, s6);
               
                /*validate saving*/
                int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to Save this record","Confirm Save",JOptionPane.YES_NO_OPTION);
        
                if (confirm != JOptionPane.YES_OPTION) {
                    return; // User cancelled1
                }
                
                int rowsaffected = pstmt.executeUpdate();
                if(rowsaffected > 0){
                    JOptionPane.showMessageDialog(null,"Record Saved Successfully");
                    clearFields();

                    comboPoultry_id.requestFocus();
                }
                else {
                    JOptionPane.showMessageDialog(this, "Failed to save record","Error",JOptionPane.ERROR_MESSAGE);
                }
}
          
          catch (SQLException ex){
              ex.printStackTrace();
}
          catch (ClassNotFoundException e){
              e.printStackTrace();
}
          finally {
                try{
                    if (st != null){
                        st.close();
                    }
                    if (con != null){
                        con.close();
                    }
                }
                catch (SQLException ex){
                    ex.printStackTrace();
                }
}
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vaccination_schedule_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vaccination_schedule_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vaccination_schedule_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vaccination_schedule_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vaccination_schedule_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboAdministered_by;
    private javax.swing.JComboBox<String> comboPoultry_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAdministered_date;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtVaccine;
    private javax.swing.JTextField txt_ID;
    // End of variables declaration//GEN-END:variables

    private void populatepoultryid() {
    Connection localCon = null;
    Statement localSt = null;
    ResultSet localRs = null;
     
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        localCon = DriverManager.getConnection(cs, user, password);
        localSt = localCon.createStatement();
        
        // Populate Poultry ID combo box
        query = "SELECT ID FROM poultry";
        localRs = localSt.executeQuery(query);
        
        DefaultComboBoxModel<String> poultryModel = new DefaultComboBoxModel<>();
        poultryModel.addElement("--Select Poultry ID--");
        while (localRs.next()) {
            poultryModel.addElement(localRs.getString("ID"));
        }
        comboPoultry_id.setModel(poultryModel);
        
        // Close the first result set
        localRs.close();
        
        // Populate Reported By combo box with User IDs
        query = "SELECT ID FROM employees";
        localRs = localSt.executeQuery(query);
        
        DefaultComboBoxModel<String> userModel = new DefaultComboBoxModel<>();
        userModel.addElement("--Select Employee ID--");
        while (localRs.next()) {
            userModel.addElement(localRs.getString("ID"));
        }
        comboAdministered_by.setModel(userModel);
        
    } catch (SQLException | ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(this, "Error loading data: " + ex.getMessage(), 
            "Database Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    } finally {
        try {
            if (localRs != null) localRs.close();
            if (localSt != null) localSt.close();
            if (localCon != null) localCon.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    }

    private void clearFields() {
        txt_ID.setText("");
        txtDate.setText("");
        comboPoultry_id.setSelectedItem("--Select Poultry ID--");
        txtVaccine.setText("");
        txtAdministered_date.setText("");
        comboAdministered_by.setSelectedItem("--Select Employee ID--");
    }
     private boolean isValidDate(String dateStr) {
        if (dateStr == null || !dateStr.matches("\\d{4}-\\d{2}-\\d{2}")) {
            return false;
        }

        try {
            java.sql.Date.valueOf(dateStr);
            return true;
        } catch (IllegalArgumentException e) {
            return false;
        }
}
}
