/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poultry_farm;

import javax.swing.JOptionPane;

/**
 *
 * @author HOOKE GEN
 */
public class Worker_form extends javax.swing.JFrame {

    /**
     * Creates new form Worker_form
     */
    public Worker_form() {
        setTitle("POULTRY FARM MANAGEMENT SYSTEM");
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEgg_collection = new javax.swing.JButton();
        Feed_consumption = new javax.swing.JButton();
        btnMortality_record = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Logged in as a  Worker");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 6, -1, -1));

        btnEgg_collection.setText("Egg Collection");
        btnEgg_collection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEgg_collectionActionPerformed(evt);
            }
        });
        getContentPane().add(btnEgg_collection, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 77, 138, -1));

        Feed_consumption.setText("Feed Consumptiuon");
        Feed_consumption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Feed_consumptionActionPerformed(evt);
            }
        });
        getContentPane().add(Feed_consumption, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 118, -1, -1));

        btnMortality_record.setText("Mortality Record");
        btnMortality_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMortality_recordActionPerformed(evt);
            }
        });
        getContentPane().add(btnMortality_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 159, 138, -1));

        btnLogin.setText("Logout");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 200, 138, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOOKE GEN\\Documents\\NetBeansProjects\\Poultry_Farm\\poultry_pictures\\farm.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMortality_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMortality_recordActionPerformed
        Mortality_record_form mortalityrecordform = new Mortality_record_form("worker");
        mortalityrecordform.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMortality_recordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        else {
            this.dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_form().setVisible(true);
            }
        });
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnEgg_collectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEgg_collectionActionPerformed
        Egg_collection_form.Main();
        this.dispose();
    }//GEN-LAST:event_btnEgg_collectionActionPerformed

    private void Feed_consumptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Feed_consumptionActionPerformed
       Feed_consumption_form feedForm = new Feed_consumption_form("worker");
       feedForm.setVisible(true);
       this.dispose();
                
    }//GEN-LAST:event_Feed_consumptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Worker_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Worker_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Worker_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Worker_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Worker_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Feed_consumption;
    private javax.swing.JButton btnEgg_collection;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMortality_record;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
